### ISSUE TITLE
获取指定页面元素的时候提示Error: socket hang up，之前的页面都没问题，就这个页面有问题

### ISSUE THREAD

**Issue by zhoutq** [macacajs/app-inspector#102]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:app-inspector@1.2.29

- os version / 系统:10.12.4

- device  information / 设备版本:10.3.1

- terminal log / 终端输出信息:

```
$ app-inspector -u xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>> port: 5678 was occupied, changed port: 5681
>> xctestwd start with port: 8001
>> XCTestWD version: 1.0.16
>> iOS device started: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>> inspector start at: http://10.10.10.105:5681
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /

  Error: socket hang up
      at createHangUpError (_http_client.js:253:15)
      at Socket.socketOnEnd (_http_client.js:345:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)



```
所有的页面都没问题，只有到这个页面就出现这个问题
> try `app-inspector -u xxxx --verbose` for more log detail.
>> iOS device started: xxxxxxxxxxxxxx
>> inspector start at: http://10.10.10.105:5681
  <-- GET /
>> ios.js:67:10 [master] pid:54667 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
  --> GET / 200
  <-- GET /
>> ios.js:67:10 [master] pid:54667 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
  --> GET / 200
  <-- GET /
>> helper.js:97:16 [master] pid:54667 xctest client proxy error with: Error: socket hang up

  Error: socket hang up
      at createHangUpError (_http_client.js:253:15)
      at Socket.socketOnEnd (_http_client.js:345:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

>> xctest-client.js:174:14 [master] pid:54667 2017-05-17 16:49:44.219 xcodebuild[54673:516182]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ztq/Library/Developer/Xcode/DerivedData/XCTestWD-axkqlenngybuncdbvpzpmscswlws/Logs/Test/69F49BF9-1EDE-4998-9848-E716A90ABFBD/Session-XCTestWDUITests-2017-05-17_164944-dptZTv.log

>> xctest-client.js:175:14 [master] pid:54667 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/._xctestwd@1.0.16@xctestwd/XCTestWD/XCTestWD.xcodeproj

**Comment by AppleZou** [comment]
@zhoutq 我也报这个错，你解决了吗？

**Comment by SamuelZhaoY** [comment]
app-inspector -u xxxx --verbose  麻烦执行这个， 才能知道具体问题
