### ISSUE TITLE
Encountered Internal Server Error upon running

### ISSUE THREAD

**Issue by adromil** [macacajs/app-inspector#117]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/local/bin/macaca -> /usr/local/lib/node_modules/macaca-cli/bin/macaca-cli

> macaca-cli@2.0.4 postinstall /usr/local/lib/node_modules/macaca-cli
> node ./scripts/print.js


@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@888@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0Lt111111tL0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0GCLCG8@01ii1fLCGGGGCC8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80GLfCfL0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80GCLLfttttt1i1tfffLCG08@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8GLti;;;;;;;;;;;;;;;;;;;;;;;;itfC0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@8Cti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i1LG8@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@0L1;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;1L0@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@8L1;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;if0@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@880088@@@@0t;;;;;;;;;;;itLCG0000GCLt1;;;;itfCGG000GCLf1;;;;;;;;;;;;1C8@@@80008@@@@@@@@@@@
@@@@@@8Cti;;;;;;itLt;;;;;;;;;;tC8@@@@@@@@@@@@@@8GC0@@@@@@@@@@@@@@8Gfi;;;;;;;;;;;t1i;;;;;i1fG8@@@@@@
@@@@0t;;;;;;;;;;;;;;;;;;;;;;L8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@C1;;;;;;;;;;;;;;;;;;;;;if8@@@@
@@@L;;;;;;;;;;;;;;;;;;;;;;t8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@C;;;;;;;;;;;;;;;;;;;;;;iG@@@
@@L;;;;;;;;;;;;;;;;;;;;;;L@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0;;;;;;;;;;;;;;;;;;;;;;;0@@
@8;;;;;;;;;;;;;;;;;;;;;;f@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@G;;;;;;;;;;;;;;;;;;;;;;1@@
@G;;;;;;;;;;;;;;;;;;;;;;8@@@@@@@@@8CfLG@@@@@@@@@@@@@@@@@8CfLC@@@@@@@@@@@@@t;;;;;;;;;;;;;;;;;;;;;i@@
@8;;;;;;;;;;;;;;;;;;;;;t@@@@@@@@@G;;;;;t@@@@@@@@@@@@@@@8i;;;;i8@@@@@@@@@@@G;;;;;;;;;;;;;;;;;;;;;1@@
@@L;;;;;;;;;;;;;;;;;;;;t@@@@@@@@@G;;;;;1@@@@@@@@@@@@@@@8;;;;;i8@@@@@@@@@@@G;;;;;;;;;;;;;;;;;;;;;0@@
@@@L;;;;;;;;;;;;;;;;;;;i@@@@@@@@@@0LtfC@@@@@@@@@@@@@@@@@8LffC8@@@@@@@@@@@@L;;;;;;;;;;;;;;;;;;;iG@@@
@@@@0t;;;;;;;;;;;;;;;;;;C@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8;;;;;;;;;;;;;;;;;;;f8@@@@
@@@@@@0Lti;;;;;;;;;;;;;;i8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Ci;;;;;;;;;;;;;;1fC8@@@@@@
@@@@@@@@@@1;;;;;;;;;;;fG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Gt;;;;;;;;;;;i@@@@@@@@@@
@@@@@@@@@@t;;;;;;;;;f8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@01;;;;;;;;;i@@@@@@@@@@
@@@@@@@@@@L;;;;;;;;G@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@f;;;;;;;;t@@@@@@@@@@
@@@@@@@@@@0;;;;;;;0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@1;;;;;;;C@@@@@@@@@@
@@@@@@@@@@@1;;;;;t@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@G;;;;;;i8@@@@@@@@@@
@@@@@@@@@@@0;;;;;L@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;;;;;;C@@@@@@@@@@@
@@@@@@@@@@@@f;;;;f@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@i;;;;t@@@@@@@@@@@@
@@@@@@@@@@@@@t;;;i@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8;;;;i8@@@@@@@@@@@@
@@@@@@@@@@@@@@t;;;t@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@t;;;i8@@@@@@@@@@@@@
@@@@@@@@@@@@@@@f;;;t8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8t;;;t8@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@Gi;;iG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Gi;;;L@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@8f;;;tG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8C1;;;t0@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@0t;;;ifG8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0Cti;;;tG@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@0fi;;;;tLG8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80Cti;;;;;f0@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@8Gt;;;;;;itfLC008@@@@@@@@@@@@@@@@@@880GCLt1;;;;;;;tC8@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@8Gf1;;;;;;;;;;ii11ttfffLffftt11ii;;;;;;;;;;itC8@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8Gfti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i1fC0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8GCLt11i;;;;;;;;;;;;;ii1tfCG0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8880000000888@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


Macaca was successfully installed! Please visit: https://macacajs.github.io

+ macaca-cli@2.0.4
updated 1 package in 130.555s

  macaca-doctor version: 2.0.1


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.1.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled
  carthage is uninstalled

  Android checklist:

(node:3835) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): exec java -version error with: Error: Command failed: java -version
No Java runtime present, requesting install.

(node:3835) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

---

- app inspector version / 版本号:  **2.0.5**

- os version / 系统: **10.3.2** (14F89)

- device  information / 设备版本: **iPhone 5S** [b0b6290d19f05c1e1ef352277eeda23df8491c86] (real device) on **MacBook Pro** (Retina, 13-inch, Early 2015) macOS Sierra Version 10.12.4 (16E195) 

- terminal log / 终端输出信息:

```
>> iOS device started: b0b6290d19f05c1e1ef352277eeda23df8491c86
>> inspector start at: http://192.168.101.140:5678
  <-- GET /
>> helper.js:94:16 [master] pid:3912 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1016:11)
      at exports._exceptionWithHostPort (util.js:1039:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
```

> try `app-inspector -u xxxx --verbose` for more log detail.

```
>> request.js:24:12 [master] pid:3792 get remote update info failed.
>> server.js:16:12 [master] pid:3792 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'b0b6290d19f05c1e1ef352277eeda23df8491c86',
  ip: '192.168.101.140',
  host: 'Adros-MacBook-Pro.local',
  loaded_time: '2017-06-14 18:22:52' }
>> app-inspector.js:43:12 [master] pid:3792 server start at: http://192.168.101.140:5678
>> xctest-client.js:52:14 [master] pid:3792 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:3792 xcode version: 8.3.3
>> xctest-client.js:247:14 [master] pid:3792 Fail to start xctest: Error: Command failed: which iproxy

>> xctest-client.js:255:14 [master] pid:3792 killing deviceLogProc pid: 3795
{ Error: Command failed: which iproxy

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:548:12) killed: false, code: 1, signal: null, cmd: 'which iproxy' }
>> iOS device started: b0b6290d19f05c1e1ef352277eeda23df8491c86
>> inspector start at: http://192.168.101.140:5678
  <-- GET /
>> helper.js:94:16 [master] pid:3792 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1016:11)
      at exports._exceptionWithHostPort (util.js:1039:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
```

**Comment by kahyalar** [comment]
Hey @adromil,

I can see you have some missing dependencies. If you look at your log and you macaca doctor file:
`Error: Command failed: which iproxy` That means you have to install iproxy. Also you have to install carthage and ios_webkit_debug_proxy. You can install them via brew. 

My suggestion is make sure you have green log output for macaca doctor, then it will work.
Let me know, if there is any good or bad news.

**Comment by govinda-raj** [comment]
Hi @kahyalar 
In my case everything is green for ios, node, device checklist. but still I am getting the same error as

> server.js:16:12 [master] pid:10090 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'e2011823e8b1a38b69a12dacedbe869d10032d7f',
  ip: '172.16.28.181',
  host: 'Coviams-MacBook-Pro-3.local',
  loaded_time: '2017-11-08 20:25:15' }
>> app-inspector.js:43:12 [master] pid:10090 server start at: http://172.16.28.181:5678
>> xctest-client.js:56:14 [master] pid:10090 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:242:14 [master] pid:10090 xcode version: 9.0.1
>> XCTestWD version: 1.3.4
>> xctest-client.js:190:18 [master] pid:10090 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:10090 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:10090 killing deviceLogProc pid: 10096
>> xctest-client.js:281:14 [master] pid:10090 killing runnerProc pid: 10093
>> xctest-client.js:201:16 [master] pid:10090 xctest client exit with code: 65, signal: null
>> xctest-client.js:155:16 [master] pid:10090 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:268:14 [master] pid:10090 Fail to start xctest: undefined
undefined
>> iOS device started: e2011823e8b1a38b69a12dacedbe869d10032d7f
>> inspector start at: http://172.16.28.181:5678
  <-- GET /
>> helper.js:94:16 [master] pid:10090 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)


Can you help me in that?

**Comment by kahyalar** [comment]
Hi @govinda-raj , as I can understand there is something happened at XCTestWD project. If you'll open that project, you have to sign this application via your license. Because, your xctest never started at all so problem must be happening in there. 

After did that, let me know 👍

**Comment by govinda-raj** [comment]
Hello @kahyalar, I have done signing in the XCTestWD project in general section via my license but still getting the same error.

> port: 5678,
  verbose: true,
  udid: 'e2011823e8b1a38b69a12dacedbe869d10032d7f',
  ip: '10.177.2.45',
  host: 'Coviams-MacBook-Pro-3.local',
  loaded_time: '2017-11-13 14:11:58' }
>> app-inspector.js:43:12 [master] pid:993 server start at: http://10.177.2.45:5678
>> xctest-client.js:56:14 [master] pid:993 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:242:14 [master] pid:993 xcode version: 9.1
>> XCTestWD version: 1.3.5
>> xctest-client.js:190:18 [master] pid:993 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:993 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:993 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:993 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:993 killing deviceLogProc pid: 999
>> xctest-client.js:281:14 [master] pid:993 killing runnerProc pid: 996
>> xctest-client.js:201:16 [master] pid:993 xctest client exit with code: 65, signal: null
>> xctest-client.js:155:16 [master] pid:993 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:268:14 [master] pid:993 Fail to start xctest: undefined
undefined
>> iOS device started: e2011823e8b1a38b69a12dacedbe869d10032d7f
>> inspector start at: http://10.177.2.45:5678
  <-- GET /
>> helper.js:94:16 [master] pid:993 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

**Comment by kahyalar** [comment]
Hi again @govinda-raj , I'm not sure about yours right now. But I want to ask something. There is more than 1 target maybe you could see in XCode. You have to sign them all.

**Comment by govinda-raj** [comment]
@kahyalar 
Hey man, thanks for the help. Actually yeah, there is more than one target like in my case it is XCTestWD andXCTestWDUITest and I signed in all. But I don't know why I am getting this again and again. I also uninstalled the things and install again but the same issue I am facing.

**Comment by kahyalar** [comment]
Did you installed like what shown in guide ? 

After I talked with you. I re-install application and it's working still properly. I'll write down my installation steps. If you want, you try one last time i guess. I'm not the maintainer of this project. I'm just trying to fix errors depending my experience. I hope we will solve this.

Steps: 
1-) Uninstall everything 
2-) Install normally via npm install -g app-inspector
3-) Open project and sign for both targets and settings(general and build) and [get your signing id](http://wx1.sinaimg.cn/large/6d308bd9gy1fg7cnt9hf6j20t70h7782.jpg) 
4-) After you signed and closed project install like this again.
`DEVELOPMENT_TEAM_ID=TEAM_ID npm i app-inspector -g`

I hope this work

**Comment by govinda-raj** [comment]
Hi @kahyalar 
You are talking about XCTestWD project?

**Comment by govinda-raj** [comment]
![screen shot 2017-11-13 at 3 31 58 pm](https://user-images.githubusercontent.com/16523696/32719908-f18f3fec-c887-11e7-8aa7-e29b5b90b10d.png)


I am getting this issue while i am installing again normally via npm install -g app-inspector.

**Comment by kahyalar** [comment]
Actually this problem is related to Android. If you are not working on Android, it won't affect you. But if you want to fix android errors, run macaca doctor and check android for all green. 👍

**Comment by govinda-raj** [comment]
Yes, I just want it for IOS only and you were talking about XCTestWD project.Right?

**Comment by kahyalar** [comment]
Yes 👍

**Comment by govinda-raj** [comment]
Thank you so much for help @kahyalar 
These are my screen shots for signing in general and build for both target.
![xctestbuild](https://user-images.githubusercontent.com/16523696/32721031-36375bfe-c88b-11e7-9303-420928854058.png)
![xctestgeneral](https://user-images.githubusercontent.com/16523696/32721032-367d8160-c88b-11e7-8b1e-eb1257eac9d5.png)
![xctestuibuild](https://user-images.githubusercontent.com/16523696/32721034-36c1c06e-c88b-11e7-8afe-c343f0a5965c.png)
![xctestuigeneral](https://user-images.githubusercontent.com/16523696/32721036-37061444-c88b-11e7-9487-b08fab6dfea8.png)
After changing the profile I build the project first, Sorry but I am still getting the same issue.

**Comment by kahyalar** [comment]
You have to get the development team id. Then run this command ` DEVELOPMENT_TEAM_ID=TEAM_ID npm i app-inspector -g`

**Comment by govinda-raj** [comment]
Yes I did.
![screen shot 2017-11-13 at 4 40 10 pm](https://user-images.githubusercontent.com/16523696/32722968-c2c4ae5e-c891-11e7-8f55-19bdb64115c4.png)

Then I run this command. I have taken screenshot.
![final error](https://user-images.githubusercontent.com/16523696/32723140-682e4b84-c892-11e7-8293-51aff6b8acb0.png)

**Comment by akshaypanambur** [comment]
I'm also facing ame issue ! Any solutions ?

**Comment by tulasikrishan89** [comment]
same issue

**Comment by tulasikrishan89** [comment]
Allow CORS implementation is required
