### ISSUE TITLE
iOS真机获取UI失败

### ISSUE THREAD

**Issue by ghost62184** [macacajs/app-inspector#119]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```
macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.11.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_25`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhangyayong/Library/Android/sdk`
  Platforms is set to `/Users/zhangyayong/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/zhangyayong/Library/Android/sdk/platform-tools/adb`
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  android: 1.0.39 [out-of-date]
  ios: 2.0.18
---

- app inspector version / 版本号:
2.0.2

- os version / 系统:
10.12.5 (16F73)

- device  information / 设备版本:
iOS 10.3.2

- terminal log / 终端输出信息:

```
>> xctestwd start with port: 8001
>> XCTestWD version: 1.0.38
undefined
>> iOS device started: 769f99d5348d321261d241462fd83f90491927d5
>> inspector start at: http://192.168.31.196:5678
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by fengguochao** [comment]
1. 麻烦更新最新版本
2. 尝试卸载手机上的Webdriver和XCTestWD
3. app-inspector -u xxxx --verbose ，麻烦加上--verbose 获取更多详细信息，贴一下
