### ISSUE TITLE
ubuntu16.04  app-inspector 失败

### ISSUE THREAD

**Issue by rubyvirus** [macacajs/app-inspector#125]
1. env: ubuntu16.04_64 
2. 执行 sudo app-inspector -u ae9cded8
3. 提示如下，已经配置过echo $ANDROID_HOME / sudo echo $ANDROID_HOME 显示正确路径
```
>> helper.js:109:12 [master] pid:31417 please set ANDROID_HOME
Error: >> helper.js:109:12 [master] pid:31417 please set ANDROID_HOME
    at Logger.error (/usr/lib/node_modules/app-inspector/node_modules/_xlogger@1.0.6@xlogger/lib/xlogger.js:169:9)
    at Object._.getAdbPath (/usr/lib/node_modules/app-inspector/node_modules/_macaca-adb@1.0.23@macaca-adb/lib/helper.js:109:12)
    at Object._.adbShell (/usr/lib/node_modules/app-inspector/node_modules/_macaca-adb@1.0.23@macaca-adb/lib/helper.js:99:21)
    at ADB.forward (/usr/lib/node_modules/app-inspector/node_modules/_macaca-adb@1.0.23@macaca-adb/lib/macaca-adb.js:110:15)
    at UIAutomator.init (/usr/lib/node_modules/app-inspector/node_modules/_uiautomatorwd@1.0.39@uiautomatorwd/lib/uiautomator-client.js:23:18)
    at next (native)
    at onFulfilled (/usr/lib/node_modules/app-inspector/node_modules/_co@4.6.0@co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)

```

**Comment by rubyvirus** [comment]
sorry it's not macaca fault
