### ISSUE TITLE
问下这个udid在android上是指的什么,成功启动服务后也一直在loading

### ISSUE THREAD

**Issue by testj** [macacajs/app-inspector#13]
我用的是`adb devices`
```
List of devices attached
203e1f90	device
```
用的`203e1f90`

**Comment by meowtec** [comment]
是 `203e1f90`

`adb -s 203e1f90  shell` 能连上去吗？

**Comment by meowtec** [comment]
log 日志呢？
贴出了看看
有没有看到
```
Android device started: 203e1f90
```
这样的内容？

**Comment by testj** [comment]
用adb链接设备正常:
```
$ adb -s 203e1f90 shell
shell@android:/ $ echo hello
hello
```
日志内容:
```
shell>app-inspector -u 203e1f90  --verbose
>> server.js:15:12 [master] pid:1891 server start with config:
 { port: 5678,
  verbose: true,
  udid: '203e1f90',
  ip: '10.6.24.99',
  host: 'XXXXXdeMacBook-Air.local',
  loaded_time: '2016-08-26 11:26:13' }
>> inspector start at: http://10.6.24.99:5678
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
```

**Comment by xudafeng** [comment]
@testj app-inspector 安装过程中如有报错，把log贴一下

**Comment by meowtec** [comment]
@xudafeng 看这个日志好像是卡在 UIAutomator 上面了

**Comment by testj** [comment]
在装这个的时候报错内容为:
```
> uiautomator-client@1.0.16 install /Users/XXXXX/git/nvm/versions/node/v6.2.0/lib/node_modules/app-inspector/node_modules/uiautomator-client
> node ./scripts/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home
Error: UI test projects can only target API 16 and above

/Users/feibaobao/git/nvm/versions/node/v6.2.0/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:164
      throw e;
      ^

Error: setup failed
    at ChildProcess.createProcess.on.code (/Users/feibaobao/git/nvm/versions/node/v6.2.0/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:120:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by xudafeng** [comment]
@testj http://macacajs.github.io/macaca/faq.html 看Android SDK版本问题

**Comment by CYsuncheng** [comment]
安装最新版本app-inspector 一样的问题，链接已经失效http://macacajs.github.io/macaca/faq.html
