### ISSUE TITLE
使用 app-inspector 解析调用百度地图定位的页面时 (iOS)，会导致测试 app 崩溃

### ISSUE THREAD

**Issue by darkmanno6** [macacajs/app-inspector#132]
* 环境信息：
> Mac：OSX 10.12.6 
> Xcode：8.3.3 
> 设备：iphone 6s /ios 10.3.3
> app-inspector：v2.0.6 (单独安装的app-inspector，没有安装macaca)
* 现象：

> 今天在使用app-inspector解析ios页面，碰到一个问题。
> 在一处页面中刷新抓取xml文件时，被测试的app必崩溃，和开发找到崩溃日志查了之后发现，崩溃是发生在百度SDK中的BMKRouteSearch这个对象。
> 和开发确认每次进去这个页面的时候确实都会调用百度的sdk，然后我使用app-inspector抓取ios页面就导致百度sdk崩溃从而导致被测app崩溃，此时app-inspector会报一个错误，如下：

```
>> helper.js:94:16 [master] pid:4053 xctest client proxy error with: Error: socket hang up
  Error: socket hang up
      at createHangUpError (_http_client.js:345:15)
      at Socket.socketOnEnd (_http_client.js:437:23)
      at emitNone (events.js:110:20)
      at Socket.emit (events.js:207:7)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

麻烦开发者查一下，app-inspector是否与百度sdk有不兼容的情况

**Comment by darkmanno6** [comment]
有人解决这个问题吗？
