### ISSUE TITLE
app-inspector (2.0.6) run error with real device   

### ISSUE THREAD

**Issue by simplefff** [macacajs/app-inspector#133]
**Environment check:**
macaca-doctor version: 2.0.2
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v8.2.1
  iOS checklist:
  Xcode Command Line Tools require version: 2347 and above
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

**- app inspector version / 版本号:**
2.06

**- os version / 系统:**
10.12

- device  information / 设备版本:
iphone 6,os system 10.0.1

- terminal log / 终端输出信息:
server.js:16:12 [master] pid:63409 server start with config:
 { port: 5678,
  verbose: true,
  udid: '16ffff85fbcb3e554ec9eef5cae797f5a401dba8',
  ip: '172.24.174.28',
  host: 'B000000104670',
  loaded_time: '2017-08-18 19:13:06' }
>> app-inspector.js:43:12 [master] pid:63409 server start at: http://172.24.174.28:5678
>> xctest-client.js:55:14 [master] pid:63409 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:228:14 [master] pid:63409 xcode version: 8.3.3
>> XCTestWD version: 1.1.6
>> xctest-client.js:178:14 [master] pid:63409 xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ id:16ffff85fbcb3e554ec9eef5cae797f5a401dba8 }

	Unsupported device specifier option.
	The device “My Mac” does not support the following options: id
	Please supply only supported device specifier options.

	Available destinations for the "XCTestWDUITests" scheme:
		{ platform:iOS Simulator, id:03CFB884-F1FF-4E1C-ACA2-5922CB3DF7E0, OS:10.3.1, name:iPad (5th generation) }
		{ platform:iOS Simulator, id:FA16B4A5-16EA-4918-9D91-801F4DBB4764, OS:10.3.1, name:iPad Air }
		{ platform:iOS Simulator, id:9C785391-E128-4423-AE57-612881B204A7, OS:10.3.1, name:iPad Air 2 }
		{ platform:iOS Simulator, id:6A539399-884E-4105-9111-240E7FC98DC9, OS:10.3.1, name:iPad Pro (9.7 inch) }
		{ platform:iOS Simulator, id:4A064B41-842F-4895-93EF-6CDD75B50062, OS:10.3.1, name:iPad Pro (10.5-inch) }
		{ platform:iOS Simulator, id:BB1B473E-F0AC-4E56-869F-6A026367E342, OS:10.3.1, name:iPad Pro (12.9 inch) }
		{ platform:iOS Simulator, id:0FB4773F-80B0-43CC-8897-330BB5D39B20, OS:10.3.1, name:iPad Pro (12.9-inch) (2nd generation) }
		{ platform:iOS Simulator, id:CD6D00ED-540B-4F19-B8F1-E50034EF6474, OS:10.3.1, name:iPhone 5 }
		{ platform:iOS Simulator, id:2BCA38FD-9C40-4ECB-A292-AC37E46DB32F, OS:10.3.1, name:iPhone 5s }
		{ platform:iOS Simulator, id:2D5B81DA-26E3-48A1-B669-BC94ADFB081D, OS:10.3.1, name:iPhone 6 }
		{ platform:iOS Simulator, id:DD816642-37AC-46EA-BA48-054E7D9858F2, OS:10.3.1, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:587B2324-0ECB-4EDB-8515-3BEE4CEA0732, OS:10.3.1, name:iPhone 6s }
		{ platform:iOS Simulator, id:7EDBA8E7-9701-4261-A444-35D28E07E1FF, OS:10.3.1, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:F4FCA350-D077-4D4B-9D4E-0810A722EF4B, OS:10.3.1, name:iPhone 7 }
		{ platform:iOS Simulator, id:329D8EC2-758F-4BAF-8D15-B86EF0DC2825, OS:10.3.1, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:55292451-6D7F-4DCC-A82E-32D7D3C4CA98, OS:10.3.1, name:iPhone SE }

	Ineligible destinations for the "XCTestWDUITests" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }

>> xctest-client.js:179:14 [master] pid:63409 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:263:14 [master] pid:63409 killing deviceLogProc pid: 63412
>> xctest-client.js:268:14 [master] pid:63409 killing runnerProc pid: 63413
>> xctest-client.js:189:14 [master] pid:63409 xctest client exit with code: 70, signal: null
>> xctest-client.js:150:16 [master] pid:63409 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:255:14 [master] pid:63409 Fail to start xctest: undefined
undefined
>> iOS device started: 16ffff85fbcb3e554ec9eef5cae797f5a401dba8
>> inspector start at: http://172.24.174.28:5678
  <-- GET /
>> helper.js:94:16 [master] pid:63409 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1024:11)
      at exports._exceptionWithHostPort (util.js:1047:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404

**Comment by simplefff** [comment]
@SamuelZhaoY is there has any solutions?
