### ISSUE TITLE
hi guys i am facing issue with macaca app-inspector

### ISSUE THREAD

**Issue by biradarpg** [macacajs/app-inspector#140]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:

- os version / 系统:

- device  information / 设备版本:

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by biradarpg** [comment]
C:\>app-inspector -u cf6535e3e --verbose
>> request.js:24:12 [master] pid:6132 get remote update info failed.
>> server.js:16:12 [master] pid:6132 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'cf6535e3e',
  ip: '10.24.76.74',
  host: 'PraveenGB-PC',
  loaded_time: '2017-09-27 06:44:19' }
>> app-inspector.js:43:12 [master] pid:6132 server start at: http://10.24.76.74:
5678
{ Error: Command failed: E:\Android_StodioApp\sdk/platform-tools/adb -s cf6535e3
e forward tcp:9001 tcp:9001

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'E:\\Android_StodioApp\\sdk/platform-tools/adb -s cf6535e3e forward tcp:9
001 tcp:9001' }
