### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by grubby2013** [macacajs/app-inspector#143]
- app inspector version / 版本号:
2.0.8

- os version / 系统:
6sp(iOS 11)

- device  information / 设备版本:
ios 11

- terminal log / 终端输出信息:
>> XCTestWD version: 1.2.5
>> xctestwd start with port: 8001
>> iOS device started: 
>> inspector start at: http://10.20.148.40:5678
  <-- GET /

  SyntaxError: Unexpected end of JSON input
      at Object.parse (native)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:53:21)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:109:7)

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xilin** [comment]
+1

**Comment by PENGZHONGLING** [comment]
+1

**Comment by tudoufenzi** [comment]
我的也是有类似问题，执行 --verbose后，错误信息是这个：
SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:53:21)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/_co@4.6.0@co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
