### ISSUE TITLE
Update optionalDepenceis uiautomator

### ISSUE THREAD

**Issue by tastafur** [macacajs/app-inspector#153]
_.trunc is not a function
      at Promise (/Users/ruben/workspace/global-engineer-app/node_modules/uiautomatorwd/lib/proxy.js:55:83)
      at WDProxy.send (/Users/ruben/workspace/global-engineer-app/node_modules/uiautomatorwd/lib/proxy.js:33:12)
      at UIAutomator.sendCommand (/Users/ruben/workspace/global-engineer-app/node_modules/uiautomatorwd/lib/uiautomator-client.js:75:21)
      at Object.exports.dumpXMLAndScreenShot (/Users/ruben/workspace/global-engineer-app/node_modules/app-inspector/lib/android.js:17:34)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/Users/ruben/workspace/global-engineer-app/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:109:7)

In proxy user _ = require helper -> and helper use xutils -> xutil inherited lodash and lodash was update version in xutil package to 4.0.0 in this version of function _.trunc is named with name _.trunced that's why it's failing

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/commit/ba76632791592f7a9c4bcb3c1c84ee8cda88d8c5

**Comment by xudafeng** [comment]
@tastafur please reinstall inspector
