### ISSUE TITLE
Issue in lauching macaca app-inspector 

### ISSUE THREAD

**Issue by akshaypanambur** [macacajs/app-inspector#158]
Hi,

Really appreciate your efforts in bringing up app-inspector.

While I was trying to use your application I encountered below issues ,please help me.

1)After installation through npm I ran the command to launch app-inspector but i faced below issue,

{ Error: Command failed: E:\AndroidSDK\trunk\android_sdk/platform-tools/adb -s 192.168.1.49:5555 push C:\Users\sachi\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'E:\\AndroidSDK\\trunk\\android_sdk/platform-tools/adb -s 192.168.1.49:5555 push C:\\Users\\sachi\\AppData\\Roaming\\npm\\node_modules\\app-inspector\\node_modules\\uiautomatorwd\\app\\build\\outputs\\apk\\app-debug.apk /data/local/tmp/com.macaca.android.testing' }

2)After thorough research I observed you have informed to execute "build.js" file under uiautomatorwd/scripts,but it throws below error while running build.js
![build](https://user-images.githubusercontent.com/32258372/33362267-a54666ca-d501-11e7-85c0-df8be9594f9e.PNG)

I'm running in windows,is there any solution ?

**Comment by akshaypanambur** [comment]
Solved by running node against the build.js file.My fault I did not add.

**Solution:**
cd to respective uiautomatorwd folder
node ./scripts/build.js
