### ISSUE TITLE
Macaca always wating device to start  on Android .

### ISSUE THREAD

**Issue by sidarakeo** [macacajs/app-inspector#160]
Anyone can help me please ? 

>> server.js:16:12 [master] pid:13404 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'myiD',
  ip: '192.168.102.18',
  host: 'DEV368-Sidara',
  loaded_time: '2017-12-26 17:24:45' }
>> app-inspector.js:43:12 [master] pid:13404 server start at: http://192.168.102.18:5678
>> uiautomator-client.js:30:12 [master] pid:13404 Error: Command failed: C:\Android\sdk/platform-tools/adb -s mydeviceid shell "pm clear "com.macaca.android.testing""
Failed

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
{ Error: Command failed: C:\Android\sdk/platform-tools/adb -s mydeviceid push C:\Users\Keo Sidara\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Android\\sdk/platform-tools/adb -s mydeviceid push C:\\Users\\Keo Sidara\\AppData\\Roaming\\npm\\node_modules\\app-inspector\\node_modules\\uiautomatorwd\\app\\build\\outputs\\apk\\app-debug.apk /data/local/tmp/com.macaca.android.testing' }

**Comment by Jagapd** [comment]
Getting same error

C:\Users\jaga_\AppData\Roaming>app-inspector -u emulator-5554
{ Error: Command failed: C:\Users\jaga_\AppData\Local\Android\sdk/platform-tools/adb -s emulator-5554 push C:\Users\jaga_\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Users\\jaga_\\AppData\\Local\\Android\\sdk/platform-tools/adb -s emulator-5554 push C:\\Users\\jaga_\\AppData\\Roaming\\npm\\node_modules\\app-inspector\\node_modules\\uiautomatorwd\\app\\build\\outputs\\apk\\app-debug.apk /data/local/tmp/com.macaca.android.testing' }

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/179

upgrade your app-inspector

**Comment by komal0708** [comment]
I am using latest version 2.0.15 of app inspector.Still getting error

>> uiautomator-client.js:37:12 [master] pid:14249 /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk not found, please resolve and reinstall android driver
Error: >> uiautomator-client.js:37:12 [master] pid:14249 /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk not found, please resolve and reinstall android driver
    at Logger.error (/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169:9)
    at UIAutomator.init (/usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/lib/uiautomator-client.js:37:12)
    at UIAutomator.init.throw (<anonymous>)
    at onRejected (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
