### ISSUE TITLE
app-inspector 启动时UIAutomatorWD client proxy error with: Error: read ECONNRESET-->com.alibaba.fastjson.JSONException: syntax error, expect [, actual undefined, pos 0

### ISSUE THREAD

**Issue by LYJHON** [macacajs/app-inspector#161]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:

2.0.
- os version / 系统:
android

- device  information / 设备版本:
android 4.4.4

- terminal log / 终端输出信息:
>> app-inspector.js:43:12 [master] pid:1940 server start at: http://192.168.70.248:8887
>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: numtests=1

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: stream=

com.macaca.android.testing.UIAutomatorWD:

INSTRUMENTATION_STATUS: id=AndroidJUnitRunner

INSTRUMENTATION_STATUS: test=MacacaTestRunner

INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD

INSTRUMENTATION_STATUS: current=1

INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: stream=
>> uiautomator-client.js:62:14 [master] pid:1940 

UIAutomatorWD->http://localhost:9002<-UIAutomatorWD

INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> Android device started: 74a52861c958
>> inspector start at: http://192.168.70.248:8887
>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: numtests=1
>> uiautomator-client.js:62:14 [master] pid:1940 

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: stream=

Error in MacacaTestRunner(com.macaca.android.testing.UIAutomatorWD):

com.alibaba.fastjson.JSONException: syntax error, expect [, actual undefined, pos 0

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1103)

>> uiautomator-client.js:62:14 [master] pid:1940 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1090)

	at com.alibaba.fastjson.JSON.parseArray(JSON.java:487)

	at com.macaca.android.testing.UIAutomatorWD.MacacaTestRunner(UIAutomatorWD.java:34)

	at java.lang.reflect.Method.invokeNative(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:515)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runners.Suite.runChild(Suite.java:128)

	at org.junit.runners.Suite.runChild(Suite.java:27)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)

	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)

	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1712)

INSTRUMENTATION_STATUS: id=AndroidJUnitRunner

INSTRUMENTATION_STATUS: test=MacacaTestRunner

INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
>> uiautomator-client.js:62:14 [master] pid:1940 

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: stack=com.alibaba.fastjson.JSONException: syntax error, expect [, actual undefined, pos 0

	
>> uiautomator-client.js:62:14 [master] pid:1940 at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1103)

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1090)

	at com.alibaba.fastjson.JSON.parseArray(JSON.java:487)

	at com.macaca.android.testing.UIAutomatorWD.MacacaTestRunner(UIAutomatorWD.java:34)

	at java.lang.reflect.Method.invokeNative(Native Method)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at java.lang.reflect.Method.invoke(Method.java:515)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runners.Suite.runChild(Suite.java:128)

	at org.junit.runners.Suite.runChild(Suite.java:27)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)

	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)

	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1712)
>> uiautomator-client.js:62:14 [master] pid:1940 

INSTRUMENTATION_STATUS: current=1

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS_CODE: -2

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_RESULT: stream=
>> uiautomator-client.js:62:14 [master] pid:1940 

Time: 0.095

There was 1 failure:

1) MacacaTestRunner(com.macaca.android.testing.UIAutomatorWD)

com.alibaba.fastjson.JSONException: syntax error, expect [, actual undefined, pos 0

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1103)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1090)

	at com.alibaba.fastjson.JSON.parseArray(JSON.java:487)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at com.macaca.android.testing.UIAutomatorWD.MacacaTestRunner(UIAutomatorWD.java:34)

	at java.lang.reflect.Method.invokeNative(Native Method)

>> uiautomator-client.js:62:14 [master] pid:1940 	at java.lang.reflect.Method.invoke(Method.java:515)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runners.Suite.runChild(Suite.java:128)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runners.Suite.runChild(Suite.java:27)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>> uiautomator-client.js:62:14 [master] pid:1940 

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

>> uiautomator-client.js:62:14 [master] pid:1940 	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)

>> uiautomator-client.js:62:14 [master] pid:1940 	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)

	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1712)

FAILURES!!!

Tests run: 1,  Failures: 1

>> uiautomator-client.js:62:14 [master] pid:1940 

>> uiautomator-client.js:62:14 [master] pid:1940 

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_CODE: -1
>> uiautomator-client.js:62:14 [master] pid:1940 

  <-- GET /
>> restart UIAutomatorWD server
>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: numtests=1
>> uiautomator-client.js:62:14 [master] pid:1940 

INSTRUMENTATION_STATUS: stream=

com.macaca.android.testing.UIAutomatorWD:

INSTRUMENTATION_STATUS: id=AndroidJUnitRunner

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: test=MacacaTestRunner

INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: current=1

INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: stream=
>> uiautomator-client.js:62:14 [master] pid:1940 

UIAutomatorWD->http://localhost:9002<-UIAutomatorWD

INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> proxy.js:55:14 [master] pid:1940 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9002/wd/hub/session/:sessionId/source:GET with body: null
>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: numtests=1

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: stream=

Error in MacacaTestRunner(com.macaca.android.testing.UIAutomatorWD):

com.alibaba.fastjson.JSONException: syntax error, expect [, actual undefined, pos 0

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1103)

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1090)

	at com.alibaba.fastjson.JSON.parseArray(JSON.java:487)

	at com.macaca.android.testing.UIAutomatorWD.MacacaTestRunner(UIAutomatorWD.java:34)

	at java.lang.reflect.Method.invokeNative(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:515)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runners.Suite.runChild(Suite.java:128)

	at org.junit.runners.Suite.runChild(Suite.java:27)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)

	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)

	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1712)

>> uiautomator-client.js:62:14 [master] pid:1940 

INSTRUMENTATION_STATUS: id=AndroidJUnitRunner

INSTRUMENTATION_STATUS: test=MacacaTestRunner

INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_STATUS: stack=com.alibaba.fastjson.JSONException: syntax error, expect [, actual undefined, pos 0

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1103)

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1090)

	at com.alibaba.fastjson.JSON.parseArray(JSON.java:487)

	at com.macaca.android.testing.UIAutomatorWD.MacacaTestRunner(UIAutomatorWD.java:34)

	at java.lang.reflect.Method.invokeNative(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:515)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runners.Suite.runChild(Suite.java:128)

	at org.junit.runners.Suite.runChild(Suite.java:27)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)

	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)

	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1712)

>> uiautomator-client.js:62:14 [master] pid:1940 

INSTRUMENTATION_STATUS: current=1

INSTRUMENTATION_STATUS_CODE: -2

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_RESULT: stream=
>> uiautomator-client.js:62:14 [master] pid:1940 

>> uiautomator-client.js:62:14 [master] pid:1940 

Time: 0.097

There was 1 failure:

1) MacacaTestRunner(com.macaca.android.testing.UIAutomatorWD)

com.alibaba.fastjson.JSONException: syntax error, expect [, actual undefined, pos 0

	
>> uiautomator-client.js:62:14 [master] pid:1940 at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1103)

	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1090)

	at com.alibaba.fastjson.JSON.parseArray(JSON.java:487)

	at com.macaca.android.testing.UIAutomatorWD.MacacaTestRunner(UIAutomatorWD.java:34)

>> uiautomator-client.js:62:14 [master] pid:1940 	at java.lang.reflect.Method.invokeNative(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:515)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	
>> uiautomator-client.js:62:14 [master] pid:1940 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.junit.runners.Suite.runChild(Suite.java:128)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runners.Suite.runChild(Suite.java:27)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.eval
>> uiautomator-client.js:62:14 [master] pid:1940 uate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

>> uiautomator-client.js:62:14 [master] pid:1940 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
>> uiautomator-client.js:62:14 [master] pid:1940 

	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)

>> uiautomator-client.js:62:14 [master] pid:1940 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1712)

>> uiautomator-client.js:62:14 [master] pid:1940 FAILURES!!!

Tests run: 1,  Failures: 1

>> uiautomator-client.js:62:14 [master] pid:1940 

>> uiautomator-client.js:62:14 [master] pid:1940 

>> uiautomator-client.js:62:14 [master] pid:1940 INSTRUMENTATION_CODE: -1

>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: socket hang up
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:1940 UIAutomatorWD client proxy error with: Error: read ECONNRESET

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by quxiaozha** [comment]
UIAutomatorWD退回到45版本，将编译的两个app-debug.apk、app-debug-androidTest.apk替换app-inspector中的，再卸载手机中的两个apk，重启即可。

**Comment by laiyuncong8404** [comment]
意思是不能使用https://github.com/xiaocong/uiautomator/tree/master/uiautomator/libs
这两个APK吗？

**Comment by laiyuncong8404** [comment]
解决了，具体操作
进入`/usr/local/lib/node_modules/app-inspector/node_modules`，删除`uiautomatorwd`文件夹,
然后执行
`npm i uiautomatorwd@1.0.45`
成功后即可。

但目前有个易用性问题，每次启动inspector后，都是新开一个chrome实例，然后新打开一个空白标签页，原来的旧版本则是在当前chrome打开一个标签页，且自动跳转到localhostip:5678。

**Comment by LYJHON** [comment]
@quxiaozha ,具体的步骤能说说不，我尝试laiyuncong8404  好像没有成功

**Comment by LYJHON** [comment]
i do as the below steps,still has the problem.
1.npm i npm i uiautomatorwd@1.0.45, install 
 at C:\Users\PC\node_modules\uiautomatorwd
2.copy the apk (C:\Users\PC\node_modules\uiautomatorwd\app\build\outputs\app-debug.apk,app-debug-androidTest.apk) to C:\Users\PC\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\
3.重启手机
@quxiaozha @laiyuncong8404

**Comment by wangzi1325** [comment]
1.0.47确实有问题  换回1.0.45就好了

**Comment by LYJHON** [comment]
@wangzi1325 具体咋操作呢？

**Comment by wangzi1325** [comment]
@LYJHON   `cd C:\Users\PC\AppData\Roaming\npm\node_modules\app-inspector\
npm un uiautomatorwd
npm i uiautomatorwd@1.0.45`

**Comment by LYJHON** [comment]
@quxiaozha @wangzi1325 @laiyuncong8404 
 thanks for your help!

**Comment by wangzi1325** [comment]
@xudafeng @SamuelZhaoY 
但是实际问题没有解决，1.0.47确实会报这个错   换回老版本只是个临时解决办法吧

**Comment by timsheng** [comment]
希望在新版本可以解决这个问题
