### ISSUE TITLE
[iOS] Physical device, browser keep present "Waiting Device start..."

### ISSUE THREAD

**Issue by ansonliao** [macacajs/app-inspector#17]
- app inspector version / 版本号: 1.2.2
- os version / 系统: Max OS X 10.11.6
- device  information / 设备版本: iPhone 6 Plus with iOS 9.3.5

Hi,
I tried to run app-inspector to iOS physical device, and found that after command run in terminal `app-inspector -u [My physical iPhone UDID]`, and then open the URL `192.168.x.x:5678`, the browser keep present "Waiting Device start...".

and I run command `macaca doctor` and got all checklist in green.

please advise how to fix.

thanks.

**Comment by meowtec** [comment]
Please add `--verbose` to get more log detail:

```
app-inspector -u identifier --verbose
```

**Comment by ansonliao** [comment]
@meowtec 

trying upgrade to 1.2.6.

command `app-inspector` run with `--verbose`:

```base
***************************************
*  version 1.2.2 is outdate           *
*  run: npm i -g app-inspector@1.2.6  *
***************************************

>> server.js:16:12 [master] pid:39013 server start with config:
 { port: 5678,
  verbose: true,
  udid: '[physical iOS device UUID]',
  ip: '192.168.2.61',
  host: 'M800-L-0051.local',
  loaded_time: '2016-08-30 18:34:52' }
>> inspector start at: http://192.168.2.61:5678
>> xctest-client.js:43:14 [master] pid:39013 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:182:12 [master] pid:39013 xcode version: 7.3.1
>> xctest-client.js:155:14 [master] pid:39013 2016-08-30 18:34:53.546 xcodebuild[39017:12446207] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:155:14 [master] pid:39013 2016-08-30 18:34:53.547 xcodebuild[39017:12446207] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ActivatePowerMode.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:155:14 [master] pid:39013 2016-08-30 18:34:55.363 xcodebuild[39017:12446207] [MT] IDETestOperationsObserverDebug: (4399B3AE-8EDA-42B5-925D-F190B2EE2E73) Beginning test session 4399B3AE-8EDA-42B5-925D-F190B2EE2E73 with Xcode 7D1014 on target <DVTiOSDevice: 0x7fd9c8d6f500> {
       		deviceSerialNumber:         C39NW0GFG5QV
       		identifier:                 [physical iOS device UUID]
       		deviceClass:                iPhone
       		deviceName:                 Anson iPhone
       		deviceIdentifier:           [physical iOS device UUID]
       		productVersion:             9.3.5
       		buildVersion:               13G36
       		deviceSoftwareVersion:      9.3.5 (13G36)
       		deviceArchitecture:         arm64
       		deviceTotalCapacity:        59567329280
       		deviceAvailableCapacity:    9722298368
       		deviceIsTransient:          NO
       		ignored:                    NO
       		deviceIsBusy:               NO
       		deviceIsActivated:          YES
       		deviceActivationState:      Activated
       		deviceType:                 <DVTDeviceType:0x7fd9cb52bcf0 Xcode.DeviceType.iPhone>
       		supportedDeviceFamilies:    (
    1
)
       		applications:              (null)
       		provisioningProfiles:      (null)
       		activityProgress:          -2
       		activityTitle:
       		hasInternalSupport:        NO
       		isSupportedOS:             YES
       		developerDiskMountError:   (null)
(null)
       	} (9.3.5 (13G36))

>> xctest-client.js:155:14 [master] pid:39013 2016-08-30 18:34:55.366 xcodebuild[39017:12446258]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ansonliao/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/989B3D86-CD91-4C7A-8519-FF35798AA9F9/Session-2016-08-30_18:34:55-L2TvXQ.log

>> xctest-client.js:155:14 [master] pid:39013 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/yh/wcbs5lw16b3dfq28ncyz28hxt3jjg4/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/1d7f44c00e10dd13ba91d3233ca113f9/[physical iOS device UUID]/ManifestCache.plist

>> proxy.js:54:14 [master] pid:39013 Proxy: /session:POST to http://192.168.11.142:8200/session:POST with body: {"desiredCapabilities":{}}
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
```

**Comment by ansonliao** [comment]
@meowtec 
after upgraded to v1.2.6, problem was not fixed.

```bash
>> server.js:16:12 [master] pid:39371 server start with config:
 { port: 5678,
  verbose: true,
  udid: '[physical iOS device UUID]',
  ip: '192.168.2.61',
  host: 'M800-L-0051.local',
  loaded_time: '2016-08-30 18:44:33' }
>> inspector start at: http://192.168.2.61:5678
>> xctest-client.js:43:14 [master] pid:39371 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:182:12 [master] pid:39371 xcode version: 7.3.1
>> xctest-client.js:155:14 [master] pid:39371 2016-08-30 18:44:34.109 xcodebuild[39375:12457371] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:155:14 [master] pid:39371 2016-08-30 18:44:34.111 xcodebuild[39375:12457371] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ActivatePowerMode.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:155:14 [master] pid:39371 2016-08-30 18:44:35.910 xcodebuild[39375:12457371] [MT] IDETestOperationsObserverDebug: (A5630938-FC8D-4286-9164-F6BEF2CA40A8) Beginning test session A5630938-FC8D-4286-9164-F6BEF2CA40A8 with Xcode 7D1014 on target <DVTiOSDevice: 0x7f88fbc70820> {
       		deviceSerialNumber:         C39NW0GFG5QV
       		identifier:                 [physical iOS device UUID]
       		deviceClass:                iPhone
       		deviceName:                 Anson iPhone
       		deviceIdentifier:           [physical iOS device UUID]
       		productVersion:             9.3.5
       		buildVersion:               13G36
       		deviceSoftwareVersion:      9.3.5 (13G36)
       		deviceArchitecture:         arm64
       		deviceTotalCapacity:        59567329280
       		deviceAvailableCapacity:    9708670976
       		deviceIsTransient:          NO
       		ignored:                    NO
       		deviceIsBusy:               NO
       		deviceIsActivated:          YES
       		deviceActivationState:      Activated
       		deviceType:                 <DVTDeviceType:0x7f88fbdb4bc0 Xcode.DeviceType.iPhone>
       		supportedDeviceFamilies:    (
    1
)
       		applications:              (null)
       		provisioningProfiles:      (null)
       		activityProgress:          -2
       		activityTitle:
       		hasInternalSupport:        NO
       		isSupportedOS:             YES
       		developerDiskMountError:   (null)
(null)
       	} (9.3.5 (13G36))

>> xctest-client.js:155:14 [master] pid:39371 2016-08-30 18:44:35.912 xcodebuild[39375:12457401]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ansonliao/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/571C5618-3763-4CC7-89DC-39DF244D78C6/Session-2016-08-30_18:44:35-4HzTGK.log

  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
>> xctest-client.js:155:14 [master] pid:39371 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/yh/wcbs5lw16b3dfq28ncyz28hxt3jjg4/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/1d7f44c00e10dd13ba91d3233ca113f9/[physical iOS device UUID]/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/ansonliao/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/yh/wcbs5lw16b3dfq28ncyz28hxt3jjg4/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.iWr2XI/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
       	dst_ipa: /var/folders/yh/wcbs5lw16b3dfq28ncyz28hxt3jjg4/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.iWr2XI/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:155:14 [master] pid:39371 __MDMDirectoryDiff_block_invoke37:1473 calling writeDictToFile with: /var/folders/yh/wcbs5lw16b3dfq28ncyz28hxt3jjg4/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.iWr2XI/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:155:14 [master] pid:39371 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/yh/wcbs5lw16b3dfq28ncyz28hxt3jjg4/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.iWr2XI/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

  <-- GET /
  --> GET / 200
>> proxy.js:54:14 [master] pid:39371 Proxy: /session:POST to http://192.168.11.142:8200/session:POST with body: {"desiredCapabilities":{}}
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
>> proxy.js:58:18 [master] pid:39371 xctest client proxy error with: Error: connect ETIMEDOUT 192.168.11.142:8200
/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> proxy.js:58:18 [master] pid:39371 xctest client proxy error with: Error: connect ETIMEDOUT 192.168.11.142:8200
    at Logger.error (/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request._callback (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
```

**Comment by meowtec** [comment]
@xudafeng 
```
connect ETIMEDOUT host:8200
```

**Comment by ansonliao** [comment]
192.168.11.142:8200 is not my local machine's IP and there is no extra parameter provided to run command `app-inspector`, only device id.

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/82

**Comment by 183181731** [comment]
app inspector version  1.2.6
Max OS X 10.11.6
iPhone 6s with iOS 9.3.5
macaca test sample run nomarl in this real device.
run inspector with command: 
```
app-inspector -u <device udid> --verbose
```

log:
```
>> port: 5678 was occupied, changed port: 5679
>> server.js:16:12 [master] pid:12789 server start with config:
 { port: 5679,
  verbose: true,
  udid: ' device udid',
  ip: '192.168.241.195',
  host: 'local name',
  loaded_time: '2016-09-08 19:00:34' }
>> inspector start at: http://192.168.241.195:5679
>> xctest-client.js:43:14 [master] pid:12789 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:183:12 [master] pid:12789 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.25
>> xctest-client.js:156:14 [master] pid:12789 2016-09-08 19:00:36.581 xcodebuild[12793:161143] [MT] IDETestOperationsObserverDebug: (1DF4EC4E-87A9-42B1-90A3-A2D1508AB439) Beginning test session 1DF4EC4E-87A9-42B1-90A3-A2D1508AB439 with Xcode 7D1014 on target <DVTiOSDevice: 0x7fde62c13f50> {
		deviceSerialNumber:         FK1QF2JTGRYC
		identifier:                 <device udid>
		deviceClass:                iPhone
		deviceName:                 my device name 
		deviceIdentifier:           <device udid>
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        59669319680
		deviceAvailableCapacity:    8122503168
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fde62b2c2e0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.5 (13G36))

>> xctest-client.js:156:14 [master] pid:12789 2016-09-08 19:00:36.583 xcodebuild[12793:161164]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/username/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/64CFFA66-4084-4D6C-BD08-B51C21E85EE3/Session-2016-09-08_19:00:36-qT8dPX.log

>> xctest-client.js:156:14 [master] pid:12789 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/c4111d682711720edf8b6c6ce92aa94a/<device udid>/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/username/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.CHfngT/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.CHfngT/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:156:14 [master] pid:12789 __MDMDirectoryDiff_block_invoke37:1473 calling writeDictToFile with: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.CHfngT/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:156:14 [master] pid:12789 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.CHfngT/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> proxy.js:54:14 [master] pid:12789 Proxy: /session:POST to http://172.18.156.69:8100/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:58:18 [master] pid:12789 xctest client proxy error with: Error: connect ECONNREFUSED 172.18.156.69:8100
/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> proxy.js:58:18 [master] pid:12789 xctest client proxy error with: Error: connect ECONNREFUSED 172.18.156.69:8100
    at Logger.error (/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request._callback (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
```

**Comment by xudafeng** [comment]
Physical device, update macaca-ios

```shell
$ npm i macaca-ios -g
```

https://github.com/alibaba/macaca/issues/42

**Comment by ansonliao** [comment]
Updated `app-inspector` to `version 1.2.9`, and installed `macaca-ios` package by `npm`, and then run command:

```bash
app-inspector -u [my device udid] --verbose
```

and then open browser, but still got `Waiting Device start...`.

and the log please check below.

```bash
dev±  app-inspector -u [device_id]] --verbose

>> server.js:16:12 [master] pid:12181 server start with config:
 { port: 5678,
  verbose: true,
  udid: '[device_id]]',
  ip: '192.168.2.61',
  host: 'example.local',
  loaded_time: '2016-09-22 12:43:02' }
>> inspector start at: http://192.168.2.61:5678
>> xctest-client.js:43:14 [master] pid:12181 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:183:12 [master] pid:12181 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.28
>> xctest-client.js:156:14 [master] pid:12181 2016-09-22 12:43:05.199 xcodebuild[12185:79690] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:156:14 [master] pid:12181 2016-09-22 12:43:05.202 xcodebuild[12185:79690] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ActivatePowerMode.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:156:14 [master] pid:12181 2016-09-22 12:43:07.483 xcodebuild[12185:79690] [MT] IDETestOperationsObserverDebug: (BCCD7F3C-D83E-4C80-9949-E7BF690FACC1) Beginning test session BCCD7F3C-D83E-4C80-9949-E7BF690FACC1 with Xcode 7D1014 on target <DVTiOSDevice: 0x7fea6c4bebc0> {
       		deviceSerialNumber:         serial_number
       		identifier:                 [device_id]]
       		deviceClass:                iPhone
       		deviceName:                 iPhone 6s iOS 9
       		deviceIdentifier:           [device_id]]
       		productVersion:             9.3.2
       		buildVersion:               13F69
       		deviceSoftwareVersion:      9.3.2 (13F69)
       		deviceArchitecture:         armv7f
       		deviceTotalCapacity:        13470674944
       		deviceAvailableCapacity:    5575835648
       		deviceIsTransient:          NO
       		ignored:                    NO
       		deviceIsBusy:               NO
       		deviceIsActivated:          YES
       		deviceActivationState:      Activated
       		deviceType:                 <DVTDeviceType:0x7fea6c3f1c50 Xcode.DeviceType.iPhone>
       		supportedDeviceFamilies:    (
    1
)
       		applications:              (null)
       		provisioningProfiles:      (null)
       		activityProgress:          -2
       		activityTitle:
       		hasInternalSupport:        NO
       		isSupportedOS:             YES
       		developerDiskMountError:   (null)
(null)
       	} (9.3.2 (13F69))

>> xctest-client.js:156:14 [master] pid:12181 2016-09-22 12:43:07.485 xcodebuild[12185:79695]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ansonliao/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/1FD04A48-1C89-4BC5-94E1-ECCF1BC85D1D/Session-2016-09-22_12:43:07-3gnOF8.log

  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
>> xctest-client.js:156:14 [master] pid:12181 writeDictToFile:1269 open failed for /var/folders/yh/wcbs5lw16b3dfq28ncyz28hxt3jjg4/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/1d7f44c00e10dd13ba91d3233ca113f9/[device_id]]/ManifestCache.plist : No such file or directory

>> xctest-client.js:156:14 [master] pid:12181 MDMCacheDirectoryManifest:1364 writeDictToFile failed to write to /var/folders/yh/wcbs5lw16b3dfq28ncyz28hxt3jjg4/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/1d7f44c00e10dd13ba91d3233ca113f9/[device_id]]/ManifestCache.plist : No such file or directory

>> xctest-client.js:156:14 [master] pid:12181 ** TEST FAILED **


>> xctest-client.js:164:14 [master] pid:12181 xctest client exit with code: 65, signal: null
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
```

please kindly help to check.

**Comment by oscarli** [comment]
I had the same issue...

**Comment by bily621** [comment]
WebDriverAgent need sign

**Comment by Test991** [comment]
@bily621, Can you please elaborate your comment about WebDriverAgent need sign. Can you please provide step by step instructions?

**Comment by meowtec** [comment]
Maybe you should take a look at https://testerhome.com/topics/5953

**Comment by xudafeng** [comment]
升级iOS驱动，参考 https://testerhome.com/topics/6314
