### ISSUE TITLE
app-inspector报错，请求帮助～

### ISSUE THREAD

**Issue by GeorgeZh** [macacajs/app-inspector#178]
- app inspector version / 版本号: 2.0.13

- os version / 系统: 10.13.2

- device  information / 设备版本: 11.2.6

- terminal log / 终端输出信息:

```>> port: 5678 was occupied, changed port: 5679
>> server.js:16:12 [master] pid:37558 server start with config:
 { port: 5679,
  verbose: true,
  udid: 'd5a0a3ee97d4b556098c03718e9d687095ac0522',
  ip: '10.0.1.170',
  host: 'GeorgeZ.local',
  loaded_time: '2018-03-07 17:23:34' }
>> app-inspector.js:45:12 [master] pid:37558 server start at: http://10.0.1.170:5679
>> xctest-client.js:56:14 [master] pid:37558 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:268:14 [master] pid:37558 Fail to start xctest: exec /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "/Library/Developer/Info.plist" error with: Error: Command failed: /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "/Library/Developer/Info.plist"
Print: Entry, "CFBundleShortVersionString", Does Not Exist

exec /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "/Library/Developer/Info.plist" error with: Error: Command failed: /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "/Library/Developer/Info.plist"
Print: Entry, "CFBundleShortVersionString", Does Not Exist

>> iOS device started: d5a0a3ee97d4b556098c03718e9d687095ac0522
>> inspector start at: http://10.0.1.170:5679
  <-- GET /
>> helper.js:94:16 [master] pid:37558 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

```

**Comment by xudafeng** [comment]
@GeorgeZh 

默认运行在5678端口，你可以杀一下进程，避免端口占用

另外你使用的是iOS真机，需要按照文档添加证书。可以先使用模拟器。
