### ISSUE TITLE
'Waiting device start' on Android real device

### ISSUE THREAD

**Issue by JacopoFerrazza** [macacajs/app-inspector#181]
Environment check:

- app inspector version / 版本号: 2.0.13

- os version / 系统: Android 7.1

- device  information / 设备版本: LG Q6

- terminal log / 终端输出信息:

```
app-inspector -u LGM7007fe7bb6 --verbose
>> request.js:11:12 [master] pid:6052 get remote update info failed.
>> server.js:16:12 [master] pid:6052 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'LGM7007fe7bb6',
  ip: '192.168.56.1',
  host: 'Jacopo-GBH',
  loaded_time: '2018-03-13 17:22:54' }
>> app-inspector.js:45:12 [master] pid:6052 server start at: http://192.168.56.1:5678
{ Error: Command failed: C:\Users\Jacopo Ferrazza\AppData\Local\Android\Sdk/platform-tools/adb -s LGM7007fe7bb6 forward tcp:9001 tcp:9001
'C:\Users\Jacopo' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:538:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Users\\Jacopo Ferrazza\\AppData\\Local\\Android\\Sdk/platform-tools/adb -s LGM7007fe7bb6 forward tcp:9001 tcp:9001' }
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /


```

**Comment by liyinchigithub** [comment]
me too

**Comment by lpj0017** [comment]
i will check

**Comment by lpj0017** [comment]
https://github.com/macacajs/macaca-adb/pull/26

I am trying to fix it, wait for me.
