### ISSUE TITLE
iOS 出现系统弹窗提示时刷新查看器出现internal error

### ISSUE THREAD

**Issue by Nymph-fan** [macacajs/app-inspector#186]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:11.2

- os version / 系统:iOS

- device  information / 设备版本:

- terminal log / 终端输出信息: 
      Error: socket hang up
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at emitNone (events.js:111:20)
      at Socket.emit (events.js:208:7)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

比如
系统允许访问照片，允许推送通知的弹窗提示

**Comment by SamuelZhaoY** [comment]
系统权限弹窗导致的问题并没有复现， 请在本地debug， 推荐方法请查看 https://github.com/macacajs/XCTestWD
<img width="1374" alt="screen shot 2018-04-29 at 8 49 55 am" src="https://user-images.githubusercontent.com/8198256/39402162-7a7bcb1a-4b8a-11e8-81a7-f9164e441db0.png">
<img width="801" alt="screen shot 2018-04-29 at 8 50 43 am" src="https://user-images.githubusercontent.com/8198256/39402163-7ad024f8-4b8a-11e8-8d00-909ba984e4e9.png">
