### ISSUE TITLE
Unable to find instrumentation target package: com.macaca.android.testing

### ISSUE THREAD

**Issue by jimmyru983** [macacajs/app-inspector#204]
>> app-inspector.js:45:12 [master] pid:1936 server start at: http://192.168.1.65
:5678
>> uiautomator-client.js:38:12 [master] pid:1936 Package com.macaca.android.test
ing is not exists,execute intsall action.
>> uiautomator-client.js:51:14 [master] pid:1936 Package com.macaca.android.test
ing.test already exists. No need reinstall.
>> uiautomator-client.js:92:14 [master] pid:1936 INSTRUMENTATION_STATUS: id=Acti
vityManagerService

>> uiautomator-client.js:92:14 [master] pid:1936 INSTRUMENTATION_STATUS: Error=Unable to find instrumentation target package: com.macaca.android.testing
INSTRUMENTATION_STATUS_CODE: -1

>> uiautomator-client.js:92:14 [master] pid:1936 android.util.AndroidException:
INSTRUMENTATION_FAILED: com.macaca.android.testing.test/android.support.test.run
ner.AndroidJUnitRunner
        at com.android.commands.am.Am.runInstrument(Am.java:1093)
        at com.android.commands.am.Am.onRun(Am.java:371)

>> uiautomator-client.js:92:14 [master] pid:1936        at com.android.internal.
os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:100)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:332)

Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:

- os version / 系统:

- device  information / 设备版本:

- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by jimmyru983** [comment]
I tried to start the app-inspection in Windows 7, device is Mi4, 

app-inspector version 2.0.21
