### ISSUE TITLE
xcode 10 not working with app-inspector

### ISSUE THREAD

**Issue by rayt8909** [macacajs/app-inspector#205]
Upgraded to xcode 10.  app-inspector not starting. information below.  please let me know if any other information is needed.  Ray

Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```
macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.9.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
TypeError: Invalid Version: 10.0
    at new SemVer (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:305:11)
    at compare (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:578:10)
    at Function.lt (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:612:10)
    at Object.exports.xcodeBuild (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:56:16)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/raytrejo/android`
  Platforms is set to `/Users/raytrejo/android/platforms/android-27`
  ADB tool is set to `/Users/raytrejo/android/platform-tools/adb`
  Command Line Tools: gradle is uninstalled

  Installed driver list:
---

- app inspector version / 版本号:
app-inspector -v
 2.0.21 

- os version / 系统:
macOS High Sierra
Version 10.13.8 (17G65)

- device  information / 设备版本:
iOS simulator iPhone X 11.4

- terminal log / 终端输出信息:
{ Error: Cannot find module 'xctestwd'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/app-inspector/lib/ios.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by ssmalan94** [comment]
is there any solution here?

**Comment by cplus02** [comment]
I am also looking for a solution for this...

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/pull/144

**Comment by bl1zz4rd** [comment]
Hello @rayt8909, can you share how to fix this? thanks!

**Comment by xudafeng** [comment]
@rayt8909 

correct, reinstall it

**Comment by bl1zz4rd** [comment]
Roger that, thanks for prompt reply
