### ISSUE TITLE
Cannot find module 'uiautomator-client'

### ISSUE THREAD

**Issue by lengyao88** [macacajs/app-inspector#21]
- app inspector version / 版本号: 1.2.6

- os version / 系统:10.11.6

- device  information / 设备版本:iPhone 6 iOS9.3

- terminal log / 终端输出信息:
clydeiMac:~ cly$ app-inspector -u E0B98126-B342-4EB3-BEAB-B7607024868
>> port: 5678 was occupied, changed port: 5682
>> inspector start at: http://192.168.3.70:5682
>> app-inspector:64:44 [master] pid:951 Error: Cannot find module 'uiautomator-client'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/app-inspector/lib/android.js:8:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
@lengyao88 安装过程报错？

**Comment by lengyao88** [comment]
不是的，我执行app-inspector -u E0B98126-B342-4EB3-BEAB-B7607024868

**Comment by meowtec** [comment]
安装的时候肯定出错了，再装一次吧。

**Comment by lengyao88** [comment]
我昨天安装完之后，可以正常使用。今天就不可以了

**Comment by meowtec** [comment]
这个错是 nodejs require 的时候报的，肯定是你的依赖出问题了。

**Comment by boxiangcen** [comment]
相同的问题，安装时报错如下
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/Indigo
United/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/
node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130

> uiautomator-client@1.0.43 install C:\Users\xiangcen.bao.JIULVXING-INC\AppData\
Roaming\npm\node_modules\app-inspector\node_modules\uiautomator-client
> node ./scripts/build.js

JAVA_HOME is set to D:\q\Java\jdk1.7.0_67
Updated
file C:\Users\\AppData\Roaming\npm\node_modules\app-in
spector\node_modules\uiautomator-client\build.xml
Buildfile: build.xml

java.io.IOException: Cannot run program "command.com": CreateProcess error=2, ??
???????
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
-at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57
)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.tools.ant.taskdefs.Property.execute(Property.java:359)Execute.java
        at org.apache.tools.ant.helper.ProjectHelperImpl$TaskHandler.finished(Pr
ojectHelperImpl.java:821)ls.ant.taskdefs.Execute.launch(Execute.java:417)
        at org.apache.tools.ant.helper.ProjectHelperImpl$AbstractHandler.endElem
ent(ProjectHelperImpl.java:300).taskdefs.Execute.getProcEnvironment(Execute.java
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source
)       at org.apache.tools.ant.taskdefs.Property.loadEnvironment(Property.java:
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unkn
own Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElemen
t(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatch
er.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
        at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.tools.ant.helper.ProjectHelperImpl.parse(ProjectHelperImpl
.java:155)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.jav
a:117)
        at org.apache.tools.ant.Main.runBuild(Main.java:597)
        at org.apache.tools.ant.Main.start(Main.java:196)
at org.apache.tools.ant.Main.main(Main.java:235)
Caused by: java.io.IOException: CreateProcess error=2, ?????????
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
        at java.lang.ProcessImpl.start(ProcessImpl.java:136)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 27 more
BUILD FAILED
file:C:/Users/xiangcen.bao.JIULVXING-INC/AppData/Roaming/npm/node_modules/app-in
spector/node_modules/uiautomator-client/build.xml:36: Unexpected element "condit
ion"

Total time: 0 seconds

@meowtec @xudafeng

**Comment by CYsuncheng** [comment]
同样的问题

**Comment by CYsuncheng** [comment]
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
/usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:177
      throw e;
      ^

Error: setup failed
    at ChildProcess.createProcess.on.code (/usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:133:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
