### ISSUE TITLE
TypeError: Cannot read property 'bounds' of undefined

### ISSUE THREAD

**Issue by Kitty2014** [macacajs/app-inspector#22]
- app inspector version / 版本号:
 1.2.6 

- os version / 系统:

10.11.6 (15G31)
- device  information / 设备版本:
ProductName: iPhone OS
ProductType: iPhone6,2
ProductVersion: 9.3.5
ProductionSOC: true

- terminal log / 终端输出信息:
Internal Server Error
```
>> inspector start at: http://192.168.57.73:5678
>> WebDriverAgent version: 1.0.25
  <-- GET /
  --> GET / 200
  <-- GET /apple-touch-icon-precomposed.png
  --> GET /apple-touch-icon-precomposed.png 404
  <-- GET /apple-touch-icon.png
  --> GET /apple-touch-icon.png 404
  <-- GET /
  --> GET / 200
  <-- GET /apple-touch-icon-precomposed.png
  --> GET /apple-touch-icon-precomposed.png 404
  <-- GET /apple-touch-icon.png
  --> GET /apple-touch-icon.png 404
  <-- GET /
  --> GET / 200
  <-- GET /apple-touch-icon-precomposed.png
  --> GET /apple-touch-icon-precomposed.png 404
  <-- GET /apple-touch-icon.png
  --> GET /apple-touch-icon.png 404
  <-- GET /
  --> GET / 200
  <-- GET /apple-touch-icon-precomposed.png
  --> GET /apple-touch-icon-precomposed.png 404
  <-- GET /apple-touch-icon.png
  --> GET /apple-touch-icon.png 404
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
>> iOS device started: 5a33f17da89bc695c224bb55f23de9a5bc692733
  <-- GET /

  TypeError: Cannot read property 'bounds' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:12:22)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:49:48)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (node.js:369:9)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404
```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by meowtec** [comment]
use:
```
app-inspector -u xxxx --verbose 
```

There will be some information like:
```
Dump iOS XML success, save to /Users/berton/.nvm/versions/node/v4.4.7/lib/node_modules/.app-inspector_npminstall/.app-inspector@1.2.6/.temp/ios.json
```

cat ios.json

**Comment by meowtec** [comment]
缺少更多信息
