### ISSUE TITLE
Error when start app inspector, Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products'

### ISSUE THREAD

**Issue by jade685** [macacajs/app-inspector#227]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

```
macaca-doctor version: 2.0.16


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.15.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yaoweiqi/Applications/android-sdk-macosx`
  Android SDK Platforms directory is not exist, please install the whole thing
  Command Line Tools: gradle is uninstalled

  Installed driver list:
```

---

- app inspector version / 版本号:  2.0.24 

- os version / 系统: MacOS Mojave 10.14.3

- device  information / 设备版本: iPhone7  os:12.1.2

- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.

```
>> server.js:16:12 [master] pid:29628 server start with config:
 { port: 5678,
  verbose: true,
  udid: '8f4ac7de8f045e70a0b8c18d1b09cf36e3de3a67',
  ip: '192.168.199.167',
  host: 'yaoweiqideMBP.lan',
  loaded_time: '2019-04-01 15:20:40' }
>> app-inspector.js:45:12 [master] pid:29628 server start at: http://192.168.199.167:5678
>> xctest-client.js:56:14 [master] pid:29628 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:283:14 [master] pid:29628 xcode version: 10.2
>> XCTestWD version: 1.4.13
>> xctest-client.js:309:14 [master] pid:29628 Fail to start xctest: Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products'
{ Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products'
    at Object.readdirSync (fs.js:786:3)
    at Promise (/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/lib/xctest-client.js:189:26)
    at new Promise (<anonymous>)
    at XCTest.startBootstrap (/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/lib/xctest-client.js:182:12)
    at startBootstrap.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:118:63)
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path:
   '/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products' }
>> iOS device started: 8f4ac7de8f045e70a0b8c18d1b09cf36e3de3a67
>> inspector start at: http://192.168.199.167:5678
  <-- GET /
>> helper.js:94:16 [master] pid:29628 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
```

I've successfully compiled XCtestWD and installed the app on iphone.

Showed 'Internal Server Error' when start app inspector.

**Comment by jade685** [comment]
I think the problem may relate to Xcode upgrade. I upgraded it few days ago and this happened.
Xcode Version is 10.2 (10E125)

**Comment by paradite** [comment]
should be fixed now, please try to reinstall app-inspector and re-run the project in Xcode.

**Comment by jade685** [comment]
Fixed. 
Thanks!
