### ISSUE TITLE
Internal Server Error ，Error: socket hang up

### ISSUE THREAD

**Issue by willisfeng** [macacajs/app-inspector#233]
页面不显示，查看app一直在下滑分页，不知道是不是加载的数据过多造成的
-------------------------------------------------------
esther:Desktop esther$ app-inspector -v

 2.0.24 
-------------------------------------------------------
<-- GET /
>> ios.js:56:10 [master] pid:99752 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
  <-- GET /
  <-- GET /
/usr/local/lib/node_modules/app-inspector/.temp/ios.json>> helper.js:94:16 [master] pid:99752 xctest client proxy error with: Error: socket hang up

  Error: socket hang up
      at createHangUpError (_http_client.js:322:15)
      at Socket.socketOnEnd (_http_client.js:425:23)
      at Socket.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

>> helper.js:94:16 [master] pid:99752 xctest client proxy error with: Error:

-------------------------------------------------------
/usr/local/lib/node_modules/app-inspector/.temp/ios.json>> helper.js:94:16 [master] pid:99752 xctest client proxy error with: Error: socket hang up

  Error: socket hang up
      at createHangUpError (_http_client.js:322:15)
      at Socket.socketOnEnd (_http_client.js:425:23)
      at Socket.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

>> helper.js:94:16 [master] pid:99752 xctest client proxy error with: Error: socket hang up

  Error: socket hang up
      at createHangUpError (_http_client.js:322:15)
      at Socket.socketOnEnd (_http_client.js:425:23)
      at Socket.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

>> helper.js:94:16 [master] pid:99752 xctest client proxy error with: Error: socket hang up

  Error: socket hang up
      at createHangUpError (_http_client.js:322:15)
      at Socket.socketOnEnd (_http_client.js:425:23)
      at Socket.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

>> helper.js:94:16 [master] pid:99752 xctest client proxy error with: Error: socket hang up

  Error: socket hang up
      at createHangUpError (_http_client.js:322:15)
      at Socket.socketOnEnd (_http_client.js:425:23)
      at Socket.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by JoffreyN** [comment]
Error: socket hang up
      at connResetException (internal/errors.js:609:14)
      at Socket.socketOnEnd (_http_client.js:463:23)
      at Socket.emit (events.js:333:22)
      at endReadableNT (_stream_readable.js:1201:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
