### ISSUE TITLE
app-inspector 连真机失败

### ISSUE THREAD

**Issue by BachWings** [macacajs/app-inspector#255]
没找到什么有用的报错信息，希望能帮忙看一下

控制台日志如下
>> xctest-client.js:206:16 [master] pid:86234

>> xctest-client.js:224:18 [master] pid:86234 2020-11-17 17:43:42.151 xcodebuild[86237:1714599]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/lidejuan/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/Run-XCTestWDUITests-2020.11.17_17-43-33-+0800.xcresult/2_Test/Diagnostics/XCTestWDUITests-575E134D-9749-43AA-8EE8-9698C7FF6006/XCTestWDUITests-84E7BABC-83D1-442D-B3E2-0F434C7694F4/Session-XCTestWDUITests-2020-11-17_174342-MvGfTM.log

>> xctest-client.js:230:20 [master] pid:86234 hitted for default mode
>> xctest-client.js:222:18 [master] pid:86234 2020-11-17 17:43:42.152 xcodebuild[86237:1714584] [MT] IDETestOperationsObserverDebug: (3C885C47-A9C5-4F47-BF37-40408DF01D5D) Beginning test session XCTestWDUITests-3C885C47-A9C5-4F47-BF37-40408DF01D5D at 2020-11-17 17:43:42.152 with Xcode 10E1001 on target 📱<DVTiOSDevice (0x7fdfd8a01a00), xxx, iPhone, 12.0.1 (16A404), 78fe1acf23525c7efc6ed35a4a959599c24df814> {
		deviceSerialNumber:         C38SVYBNHFXW
		identifier:                 78fe1acf23525c7efc6ed35a4a959599c24df814
		deviceClass:                iPhone
		deviceName:                 xxx
		deviceIdentifier:           78fe1acf23525c7efc6ed35a4a959599c24df814
		productVersion:             12.0.1
		buildVersion:               16A404
		deviceSoftwareVersion:      12.0.1 (16A404)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        123608469504
		deviceAvailableCapacity:    33802158080
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsPaired:             YES
		de...
>> xctest-client.js:233:20 [master] pid:86234 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:86234 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{}}
>> xctest-client.js:270:16 [master] pid:86234 Invalid listen port specified in argument '8001'!

>> xctest-client.js:279:14 [master] pid:86234 iproxy exit with code: 234, signal: null
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:224:18 [master] pid:86234 2020-11-17 17:43:42.311 xcodebuild[86237:1714584] [MT] IDETestOperationsObserverDebug: (3C885C47-A9C5-4F47-BF37-40408DF01D5D) Finished requesting crash reports. Continuing with testing.

>> xctest-client.js:233:20 [master] pid:86234 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> helper.js:20:18 [master] pid:86234 retrying... (10 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:86234 retrying... (9 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:224:18 [master] pid:86234 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/7g/d91zf5gx4gl4m0j644h1vsfw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/9362bf04239d96846d213ed62065fb6e/78fe1acf23525c7efc6ed35a4a959599c24df814/ManifestCache.plist

>> xctest-client.js:233:20 [master] pid:86234 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> helper.js:20:18 [master] pid:86234 retrying... (8 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:86234 retrying... (7 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:86234 retrying... (6 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:86234 retrying... (5 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:86234 retrying... (4 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:86234 retrying... (3 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:86234 retrying... (2 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:86234 retrying... (1 retries left)
>> proxy.js:63:22 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:316:14 [master] pid:86234 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:329:14 [master] pid:86234 killing runnerProc pid: 86237
>> xctest-client.js:335:14 [master] pid:86234 killing iproxyProc pid: 86498
Error: connect ECONNREFUSED 127.0.0.1:8001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8001
}
>> iOS device started: 78fe1acf23525c7efc6ed35a4a959599c24df814
>> inspector start at: http://192.168.143.10:5678
>> xctest-client.js:245:16 [master] pid:86234 xctest client exit with code: null, signal: SIGKILL
  <-- GET /
>> helper.js:94:16 [master] pid:86234 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Comment by Shaobo-Zhang-Bose** [comment]
Is there a way to fix or workaroud this issue. I saw the same issue. 
Thanks
