### ISSUE TITLE
操作设备应用后刷新app-inspector页面，无法加载

### ISSUE THREAD

**Issue by Frozenaria** [macacajs/app-inspector#39]
操作设备应用后刷新app-inspector页面，无法加载

- app inspector version / 版本号:
1.2.14

- os version / 系统:
10.11.6

- device  information / 设备版本:
9.3.1

- terminal log / 终端输出信息:

```
>> ios.js:67:10 [master] pid:14175 Dump iOS XML success, save to /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.14@app-inspector/.temp/ios.json
  --> GET / 200
  <-- GET /
  <-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'origin' of undefined
      at node (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.14@app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.14@app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19)
      at process._tickCallback (node.js:379:9)
```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.14@app-inspector/.temp/ios.json

是什么

**Comment by meowtec** [comment]
这个就是之前出现多次的 bug，wda 拿不到正确的树结构

**Comment by meowtec** [comment]
JSON 我已经打印出来了：

{"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}

**Comment by xudafeng** [comment]
@Frozenaria 是打不开，不是到特定页面解析错误

**Comment by xudafeng** [comment]
升级到10以上呢？

**Comment by Frozenaria** [comment]
@xudafeng 后面又看了一下是特定页面解析错误，这个问题有解决办法了吗？

**Comment by xudafeng** [comment]
@Frozenaria 与App有关，暂时没有别的办法，等iOS新驱动研发完成会有办法解决

**Comment by FrendEr** [comment]
mark，ios 手淘出现同样的问题，app 直接 crash 掉了
