### ISSUE TITLE
在客户端的首页-登录页面，查找元素报错

### ISSUE THREAD

**Issue by wenshi11019** [macacajs/app-inspector#43]
- app inspector version / 版本号:1.2.15

- os version / 系统:10.12.1

- device  information / 设备版本:9.3（模拟器）

- terminal log / 终端输出信息:

```
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'origin' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

> 启动 app-inspector 正常，检查页面也正常，但启动到需要测试的客户端的登录页（启动客户端后自动进入的页面），就发生报错

**Comment by meowtec** [comment]
webdriverAgent 拿不到页面结构数据，是因为登录页面加了什么安全性配置吗？建议问问开发

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/56

**Comment by xudafeng** [comment]
@wenshi11019 用什么App可以复现？

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/60

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/53

**Comment by wenshi11019** [comment]
@xudafeng 用 和留言 app。还有[https://github.com/macacajs/app-inspector/issues/55](url)，报错信息也是一样的

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/55

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/477

**Comment by xudafeng** [comment]
@SamuelZhaoY 有一系列这类问题，之前我们也遇到了

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/377

**Comment by xudafeng** [comment]
update
