### ISSUE TITLE
pageSource解析错误

### ISSUE THREAD

**Issue by qq386169040** [macacajs/app-inspector#48]
- app inspector version / 版本号: 1.2.17 

- os version / 系统: OS 10.11.6

- device  information / 设备版本:iPhone6s 9.3.1   iPad Air2 10.1.1

- terminal log / 终端输出信息:

```
<-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {375, 667}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {375, 667}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {375, 667}}","rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {375, 667}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {375, 667}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{119, 45}, {115, 37}}","rect":{"y":45,"x":119,"width":115,"height":37},"value":null,"label":"TextField1","type":"TextField","name":"IntegerA","rawIdentifier":"IntegerA"},{"isEnabled":"1","isVisible":"1","frame":"{{119, 90}, {115, 38}}","rect":{"y":90,"x":119,"width":115,"height":38},"value":null,"label":"TextField2","type":"TextField","name":"IntegerB","rawIdentifier":"IntegerB"},{"isEnabled":"1","isVisible":"1","frame":"{{110, 143}, {133, 45}}","rect":{"y":143,"x":110,"width":133,"height":45},"value":null,"label":"Compute Sum","type":"Button","name":"ComputeSumButton","rawIdentifier":"ComputeSumButton"},{"isEnabled":"1","isVisible":"1","frame":"{{151, 196}, {50, 25}}","rect":{"y":196,"x":151,"width":50,"height":25},"value":"SumLabel","label":"SumLabel","type":"StaticText","name":"Answer","rawIdentifier":"Answer"},{"isEnabled":"1","isVisible":"1","frame":"{{30, 243}, {90, 52}}","rect":{"y":243,"x":30,"width":90,"height":52},"value":null,"label":"show alert","type":"Button","name":"show alert","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{128, 251}, {102, 36}}","rect":{"y":251,"x":128,"width":102,"height":36},"value":null,"label":"contact alert","type":"Button","name":"contact alert","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{239, 251}, {105, 36}}","rect":{"y":251,"x":239,"width":105,"height":36},"value":null,"label":"location alert","type":"Button","name":"location alert","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{142, 304}, {67, 25}}","rect":{"y":304,"x":142,"width":67,"height":25},"value":"AppElem","label":"AppElem","type":"StaticText","name":"AppElem","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{106, 338}, {139, 35}}","rect":{"y":338,"x":106,"width":139,"height":35},"value":"50%","label":"AppElem","type":"Slider","name":"AppElem","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{274, 341}, {35, 26}}","rect":{"y":341,"x":274,"width":35,"height":26},"value":null,"label":null,"type":"StaticText","name":"Access'ibility","rawIdentifier":"Access'ibility"},{"isEnabled":"1","isVisible":"1","frame":"{{142, 373}, {67, 25}}","rect":{"y":373,"x":142,"width":67,"height":25},"value":"AppElem","label":"AppElem","type":"StaticText","name":"AppElem","rawIdentifier":null},{"isEnabled":"0","isVisible":"1","frame":"{{97, 407}, {160, 34}}","rect":{"y":407,"x":97,"width":160,"height":34},"value":null,"label":"disabled button","type":"Button","name":"DisabledButton","rawIdentifier":"DisabledButton"},{"isEnabled":"1","isVisible":"1","frame":"{{96, 449}, {86, 26}}","rect":{"y":449,"x":96,"width":86,"height":26},"value":null,"label":null,"type":"StaticText","name":null,"rawIdentifier":null},{"isEnabled":"0","isVisible":"1","frame":"{{199, 443}, {60, 37}}","rect":{"y":443,"x":199,"width":60,"height":37},"value":true,"label":"locationStatus","type":"Switch","name":"locationStatus","rawIdentifier":"locationStatus"},{"isEnabled":"1","isVisible":"1","frame":"{{108, 465}, {137, 53}}","rect":{"y":465,"x":108,"width":137,"height":53},"value":null,"label":"Test Gesture","type":"Button","name":"Test Gesture","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{280, 474}, {49, 36}}","rect":{"y":474,"x":280,"width":49,"height":36},"value":null,"label":"Crash","type":"Button","name":"Crash","rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {375, 667}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {375, 25}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {375, 25}}","rect":{"y":0,"x":0,"width":375,"height":25},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {375, 25}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{7, 0}, {63, 25}}","rect":{"y":0,"x":7,"width":63,"height":25},"value":null,"label":"无 SIM 卡","type":"Other","name":"无 SIM 卡","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{75, 0}, {16, 25}}","rect":{"y":0,"x":75,"width":16,"height":25},"value":"SSID","label":"3 of 3 WLAN bars","type":"Other","name":"3 of 3 WLAN bars","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{160, 0}, {61, 25}}","rect":{"y":0,"x":160,"width":61,"height":25},"value":null,"label":"下午1:48","type":"Other","name":"下午1:48","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{253, 0}, {15, 25}}","rect":{"y":0,"x":253,"width":15,"height":25},"value":null,"label":"Orientation Locked","type":"Other","name":"Orientation Locked","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{274, 0}, {10, 25}}","rect":{"y":0,"x":274,"width":10,"height":25},"value":null,"label":"Bluetooth on","type":"Other","name":"Bluetooth on","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{290, 0}, {80, 25}}","rect":{"y":0,"x":290,"width":80,"height":25},"value":null,"label":"100% battery power, On AC Power","type":"Other","name":"100% battery power, On AC Power","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{290, 0}, {37, 25}}","rect":{"y":0,"x":290,"width":37,"height":25},"value":null,"label":"100% battery power","type":"Other","name":"100% battery power","rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":25},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":25},"value":null,"label":null,"type":"StatusBar","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":"TestApp","type":"Application","name":"TestApp","rawIdentifier":null}},"sessionId":"4EF084A2-2DFA-46BD-A35F-E00C063C65A4","status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'x' of undefined
      at node (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:16)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:65:19)
      at process._tickCallback (node.js:385:9)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404
```

**Comment by meowtec** [comment]
fix at 1.2.18
