### ISSUE TITLE
Can not access the link after I open my app

### ISSUE THREAD

**Issue by lina1** [macacajs/app-inspector#53]
- app inspector version / 版本号:
app-inspector@1.2.18
- os version / 系统:
10.2
- device  information / 设备版本:
simulator
iphone 7 
- terminal log / 终端输出信息:
After I open my app,  I access the website and get the following error log. 
```
 ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'x' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)


  <-- GET /favicon.ico
  --> GET /favicon.ico 404
  <-- GET /
```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by meowtec** [comment]
什么应用什么页面遇到的问题？

**Comment by lina1** [comment]
打开自己的app后，访问5678端口出现的问题 @meowtec

**Comment by meowtec** [comment]
这是因为你的应用的这个页面拿不到 xml 树结构

**Comment by PetrMr** [comment]
Hi,
if I translate it well, is it problem my app?
Because I get the same error and app crashes.

The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'x' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

- app-inspector version - 1.2.18

- macOS- 10.12.2

- simulator - iOS 10.2


I was trying this also on older macOS 10.11, simulator iOS 9.3, but with the same error.

Thank you

**Comment by xudafeng** [comment]
@PetrMr How to get this error？

**Comment by xudafeng** [comment]
@lina1 我想本地复现一下，能否提供App试一下

**Comment by xudafeng** [comment]
update
