### ISSUE TITLE
不支持Nexus 6 Android 7.0 版本号：NBD90Z 系统

### ISSUE THREAD

**Issue by wangyunshuai** [macacajs/app-inspector#54]
**真机问题先参考 https://testerhome.com/topics/5953**

#### 相同环境下，使用三星 A9100 Android 6.0.1系统，没有问题

- app inspector version / 版本号:
1.2.18

- os version / 系统: 
Mac 10.12.1

- device  information / 设备版本: 
Nexus 6
版本号：NBD90Z

- terminal log / 终端输出信息: 

```
➜  ~ app-inspector -u ZX1G423SCH —-verbose
Warning: This version of UI Automator is deprecated. New tests should be written using
UI Automator 2.0 which is available as part of the Android Testing Support Library.
See https://developer.android.com/training/testing/ui-testing/uiautomator-testing.html
for more details.

INSTRUMENTATION_STATUS: numtests=1

INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: test=testStartServer
INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize

INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1
uiautomator start socket server.

>> socket server ready
>> socket client ready
>> Android device started: ZX1G423SCH
>> inspector start at: http://172.16.24.87:5678
  <-- GET /
recive: {"cmd":"getSource","args":{}}


return: {"success":true,"data":{"status":0,"value":true}}


  Error: Command failed: /bin/sh -c /Users/smzdm/Documents/01_Android/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s ZX1G423SCH shell "cat /data/local/tmp/macaca-dump.xml"
  /system/bin/sh: cat: /data/local/tmp/macaca-dump.xml: No such file or directory

      at ChildProcess.exithandler (child_process.js:203:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:818:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at Pipe._onclose (net.js:469:12)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404
```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
@wangyunshuai 能否帮忙定位下这台手机的tmp目录是不是 /data/local/tmp/？

**Comment by wangyunshuai** [comment]
@xudafeng 是的
```shell
➜  ~ adb shell getprop ro.product.model
Nexus 6
➜  ~ adb shell
shamu:/ $ cd /data/local/tmp
shamu:/data/local/tmp $
```

**Comment by wangyunshuai** [comment]
@xudafeng 刚又找了一下, 生成到这个目录下面了
```shell
shamu:/data/local/tmp/local/tmp $ ls -l
total 80
-rw-rw-rw- 1 shell shell 40868 2016-08-28 18:52 macaca-dump.xml
```

**Comment by xudafeng** [comment]
@wangyunshuai 多谢反馈，我想办法兼容这个bug

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/51

**Comment by xudafeng** [comment]
@wangyunshuai 

@CodeToSurvive1 在fix

**Comment by CodeToSurvive1** [comment]
@wangyunshuai  npm install app-inspector -g

**Comment by wangyunshuai** [comment]
@CodeToSurvive1 好的，我试试

**Comment by wangyunshuai** [comment]
@CodeToSurvive1 Nexus 6 7.0 系统 ok 了

**Comment by huangejuan** [comment]
更新完app-insepctor 1.2.19版本，启动app-inspector -u xxx,三星S6的机型，华为6P 都异常了，
Error in testStartServer:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.uiautomator.client.CommandBase.execute(org.json.JSONObject)' on a null object reference
        at com.android.uiautomator.client.Command.handleInput(Command.java:49)
        at com.android.uiautomator.client.SocketServer.listen(SocketServer.java:60)
        at com.android.uiautomator.client.Initialize.testStartServer(Initialize.java:28)
        at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
        at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
        at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
        at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)

**Comment by CodeToSurvive1** [comment]
@huangejuan 感觉编译有问题呢 你把app-inspector删掉重新下载下试试

**Comment by huangejuan** [comment]
@CodeToSurvive1 重新下载了一次，现在可以。但是华为 google Nexus 6P的机子，用来跑脚本，无法启动server

**Comment by CodeToSurvive1** [comment]
@huangejuan  详细日志吧
