### ISSUE TITLE
出现报错TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by thanksdanny** [macacajs/app-inspector#60]
- app inspector version / 版本号:1.2.19

- os version / 系统: Mac OS

- device  information / 设备版本: iOS 9

- terminal log / 终端输出信息:

```
>> xctest-client.js:171:14 [master] pid:2422 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> iOS device started: fd779ec1e9eb20bf6c875a7c3733e31fcb120529
>> inspector start at: http://172.26.35.1:5678
  <-- GET /
>> ios.js:67:10 [master] pid:2422 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
  --> GET / 200
  <-- GET /
  <-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'x' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

```

不知为何，进入自家app后，刷新页面，终端一直没有响应。过了一段时间后出现上述报错。
其他App都是正常的，但自己app不知为何会出现报错，而且之前在自家也没出现过着情况

**Comment by xudafeng** [comment]
@thanksdanny 什么App 我如何复现呢？
