### ISSUE TITLE
app-inspector上的xpath获取页面元素，unable to find an element

### ISSUE THREAD

**Issue by Tracydeng** [macacajs/app-inspector#61]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:1.2.19

- os version / 系统:10.12.3

- device  information / 设备版本: 模拟器6s   10.2

- terminal log / 终端输出信息:

 1. Server端log:
```
Send HTTP Respone to Client: {"sessionId":"b9dfb298-6b61-402c-b359-1f8912db3412","status":0,"value":"{\"deviceName\":\"iPhone 6s\",\"autoAcceptAlerts\":\"true\",\"automationName\":\"xcuitest\",\"autoDismissAlerts\":\"true\",\"waitForAppScript\":\"$.delay(5000); $.acceptAlert();\",\"platformVersion\":\"10.2\",\"app\":\"/Users/iSteven/iSteven/AppiumProject/Xcode8.2.1_iOS10.2/Debug/FFProject.app\",\"platformName\":\"iOS\",\"showIOSLog\":\"true\"}"}
>> responseHandler.js:11:12 [master] pid:85949 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/b9dfb298-6b61-402c-b359-1f8912db3412/element, jsonBody: {"using":"xpath","sessionId":"b9dfb298-6b61-402c-b359-1f8912db3412","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]"}
>> proxy.js:56:14 [master] pid:85949 Proxy: /wd/hub/session/b9dfb298-6b61-402c-b359-1f8912db3412/element:POST to http://10.180.186.250:8900/session/BB3FF900-56EC-4A52-B967-48E49D377CBB/element:POST with body: {"using":"xpath","sessionId":"b9dfb298-6b61-402c-b359-1f8912db3412","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeAlert[1]/XCUIElementType...
>> proxy.js:84:20 [master] pid:85949 Got response with status 200: {"value":{"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIEleme...
>> session.js:107:14 [master] pid:85949 Send HTTP Respone to Client: {"value":"{\"using\":\"xpath\",\"value\":\"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeAlert[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]\",\"description\":\"unable to find an element\"}","sessionId":"b9dfb298-6b61-402c-b359-1f8912db3412","status":7}
>> responseHandler.js:11:12 [master] pid:85949 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/b9dfb298-6b61-402c-b359-1f8912db3412/element, jsonBody: {"using":"xpath","sessionId":"b9dfb298-6b61-402c-b359-1f8912db3412","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[4]/XCUIElementTypeOther[1]"}
>> proxy.js:56:14 [master] pid:85949 Proxy: /wd/hub/session/temp/accept_alert:POST to http://10.180.186.250:8900/session/BB3FF900-56EC-4A52-B967-48E49D377CBB/accept_alert:POST with body: {}
>> proxy.js:84:20 [master] pid:85949 Got response with status 200: {"value":{},"sessionId":"temp","status":0}
>> proxy.js:56:14 [master] pid:85949 Proxy: /wd/hub/session/b9dfb298-6b61-402c-b359-1f8912db3412/element:POST to http://10.180.186.250:8900/session/BB3FF900-56EC-4A52-B967-48E49D377CBB/element:POST with body: {"using":"xpath","sessionId":"b9dfb298-6b61-402c-b359-1f8912db3412","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementType...
>> proxy.js:84:20 [master] pid:85949 Got response with status 200: {"value":{"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIEleme...
>> session.js:107:14 [master] pid:85949 Send HTTP Respone to Client: {"value":"{\"using\":\"xpath\",\"value\":\"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XC...","sessionId":"b9dfb298-6b61-402c-b359-1f8912db3412","status":7}
>> responseHandler.js:11:12 [master] pid:85949 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/b9dfb298-6b61-402c-b359-1f8912db3412, jsonBody: {}
>> macaca-ios.js:336:10 [master] pid:85949 Stoping iOS driver...
>> xctest-client.js:267:14 [master] pid:85949 killing deviceLogProc pid: 89951
>> xctest-client.js:272:14 [master] pid:85949 killing runnerProc pid: 89952
>> macaca-ios.js:360:10 [master] pid:85949 iOS driver cleaned up.
>> session.js:80:12 [master] pid:85949 Delete session, sessionId: b9dfb298-6b61-402c-b359-1f8912db3412
>> responseHandler.js:47:14 [master] pid:85949 Send HTTP Respone to Client: {"sessionId":"b9dfb298-6b61-402c-b359-1f8912db3412","status":0}

```
 2. clientdu
```
test_ui_login (__main__.SimpleIOSTests) ... Traceback (most recent call last):
  File "guiyang_register2.py", line 163, in test_ui_login
    mine_el = self.driver.find_element_by_xpath("//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[4]/XCUIElementTypeOther[1]");
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
NoSuchElementException: Message: 


ok

----------------------------------------------------------------------
Ran 1 test in 31.772s

OK

```
> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by Tracydeng** [comment]
后面发现是页面元素还没加载完就已经执行了find_element方法导致，稍微延时就可以
