### ISSUE TITLE
inspector重新加载某些页面时提示Internal Server Error

### ISSUE THREAD

**Issue by yananyoungcy** [macacajs/app-inspector#63]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:1.2.20

- os version / 系统:MacOS 10.11.6

- device  information / 设备版本:  iPhone6模拟器

- terminal log / 终端输出信息:

```
 TypeError: Cannot read property 'x' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xiaoxiao257** [comment]
我也遇到同样的问题

**Comment by xudafeng** [comment]
@xiaoxiao257 升级新版
