### ISSUE TITLE
   TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Sandu1213** [macacajs/app-inspector#64]
- app inspector version / 版本号:  
 1.2.20

- os version / 系统:
10.11.6

- device  information / 设备版本:
ipad mini2(10.1.1)

- terminal log / 终端输出信息:

```
>> iOS device started: 45b6121478cbe4ee08e50cbdf63de8a0748052a1
>> inspector start at: http://192.168.22.55:5678
  <-- GET /
  <-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":"There is no active application","sessionId":null,"status":13}
    '****** xctest source end *******

  TypeError: Cannot read property 'type' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:23:20)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by xudafeng** [comment]
@Sandu1213 升级新版
