### ISSUE TITLE
更新1.2.23后，socket hang up！重装重现

### ISSUE THREAD

**Issue by grubby2013** [macacajs/app-inspector#65]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:

1.2.23
- os version / 系统:

10.2.1
- device  information / 设备版本:

iPhone 6
- terminal log / 终端输出信息:

>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.1.3
>> app-inspector:66:44 [master] pid:2981 Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(node:2981) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:2981 Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by grubby2013** [comment]
>> proxy.js:56:14 [master] pid:5411 Proxy: /session:POST to http://127.0.0.1:8900/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:62:22 [master] pid:5411 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:5411 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:5411 xctest client proxy error with: Error: socket hang up

**Comment by daisyzou** [comment]
我也遇到了这个问题，和上面的输出是一样的，求解决办法，之前装的1.2.20版本是ok的，这次按照同样的方法就失败了  多次反复重装卸载依然不能解决问题

**Comment by xudafeng** [comment]
@grubby2013 升级新版驱动

**Comment by leemony** [comment]
已升级macaca-ios 但还是没有解决 Error: socket hang up

**Comment by leemony** [comment]
虽然报错 Error: socket hang up，但是WDA是可以运行的，终端输入 curl -X GET -H "Content-Type: application/json"  http://**.**.**.**:8100/status，能够正确返回状态
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iPhone OS",
      "version" : "9.1"
    },
    "ios" : {
      "simulatorVersion" : "9.1",
      "ip" : "**.**.**.**"
    },
    "build" : {
      "time" : "Apr  7 2017 17:27:41"
    }
  },
  "sessionId" : "E144AE25-DB8E-4ABC-91F6-7179A7A8A6B1",
  "status" : 0
}

**Comment by leemony** [comment]
重装驱动后，再次重装app-inspector，Error: socket hang up 已解决，谢谢作者
