### ISSUE TITLE
安装提示android命令报错, WebDriverAgent解压失败

### ISSUE THREAD

**Issue by magaofei** [macacajs/app-inspector#69]
```shell
cnpm i install -g app-inspector
✔ All packages installed (1 packages installed from npm registry, use 392ms, speed 3.64kB/s, json 1(1.43kB), tarball 0B)
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "create uitest-project -n uiautomator-bootstrap -t android-24 -p ."
Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.9@uiautomator-client/scripts/build.js:177
      throw e;
      ^

Error: setup failed
    at ChildProcess.createProcess.on.code (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.9@uiautomator-client/scripts/build.js:133:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
app-inspector@1.2.23 › uiautomator-client@1.1.9 optional error: Error: Run "sh -c node ./scripts/build.js" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
deprecate app-inspector@1.2.23 › uiautomator-client@1.1.9 › win-spawn@2.0.0 use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
deprecate app-inspector@1.2.23 › xutil@1.0.3 › node-uuid@1.4.8 Use uuid module instead
deprecate app-inspector@1.2.23 › xctest-client@1.1.1 › request@2.69.0 › tough-cookie@2.2.2 ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
deprecate app-inspector@1.2.23 › webdriveragent@1.1.6 › xcode@0.8.9 › node-uuid@1.4.7 Use uuid module instead
✔ All packages installed (256 packages installed from npm registry, use 7s, speed 68.73kB/s, json 305(488.03kB), tarball 0B)
Recently updated (since 2017-03-31): 10 packages (detail see file node_modules/.recently_updates.txt)
  Today:
    → app-inspector@1.2.23 › xctest-client@1.1.1 (15:03:00)
    → app-inspector@1.2.23 › webdriveragent@1.1.6 (16:11:13)
    → app-inspector@1.2.23 › xutil@1.0.3 › rimraf@2.5.4 › glob@7.1.1 › minimatch@3.0.3 › brace-expansion@1.1.7 (16:13:51)
    → app-inspector@1.2.23 › nunjucks@2.5.2 › chokidar@1.6.1 › readdirp@2.1.0 › readable-stream@2.2.7 (15:45:02)

```

我运行提示
```shell
app-inspector -u 4fde6542011bd1a001a41edac73f0e492af603b4 --verbose
>> server.js:16:12 [master] pid:13309 server start with config:
 { port: 5678,
  verbose: true,
  udid: '4fde6542011bd1a001a41edac73f0e492af603b4',
  ip: '10.1.29.224',
  host: 'localhost',
  loaded_time: '2017-04-07 17:26:20' }
>> app-inspector.js:42:10 [master] pid:13309 server start at: http://10.1.29.224:5678
>> xctest-client.js:58:14 [master] pid:13309 project path not found
>> app-inspector:66:44 [master] pid:13309 Error: >> xctest-client.js:58:14 [master] pid:13309 project path not found
    at Logger.error (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.6@xlogger/lib/xlogger.js:169:9)
    at XCTest.checkProjectPath (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.1@xctest-client/lib/xctest-client.js:58:14)
    at XCTest.init (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.1@xctest-client/lib/xctest-client.js:51:10)
    at XCTest (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.1@xctest-client/lib/xctest-client.js:39:10)
    at Object.exports.initDevice (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.23@app-inspector/lib/ios.js:90:12)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:54:5
    at co (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:118:63)
(node:13309) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: >> app-inspector:66:44 [master] pid:13309 Error: >> xctest-client.js:58:14 [master] pid:13309 project path not found
    at Logger.error (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.6@xlogger/lib/xlogger.js:169:9)
    at XCTest.checkProjectPath (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.1@xctest-client/lib/xctest-client.js:58:14)
    at XCTest.init (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.1@xctest-client/lib/xctest-client.js:51:10)
    at XCTest (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.1@xctest-client/lib/xctest-client.js:39:10)
    at Object.exports.initDevice (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.23@app-inspector/lib/ios.js:90:12)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:54:5
    at co (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:118:63)

```

接着导致解压失败，我找到了相关文件，解压签名后，再次运行命令

```shell

app-inspector -u 4fde6542011bd1a001a41edac73f0e492af603b4 --verbose
>> server.js:16:12 [master] pid:14054 server start with config:
 { port: 5678,
  verbose: true,
  udid: '4fde6542011bd1a001a41edac73f0e492af603b4',
  ip: '10.1.29.224',
  host: 'localhost',
  loaded_time: '2017-04-07 17:36:59' }
>> app-inspector.js:42:10 [master] pid:14054 server start at: http://10.1.29.224:5678
>> xctest-client.js:56:14 [master] pid:14054 project path: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client start with port: 8900
>> xctest-client.js:238:14 [master] pid:14054 xcode version: 8.3
>> WebDriverAgent version: 1.1.6
>> xctest-client.js:175:14 [master] pid:14054 2017-04-07 17:36:59.900 xcodebuild[14060:2105388] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:14054 2017-04-07 17:36:59.900 xcodebuild[14060:2105388] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:14054 2017-04-07 17:37:00.720 xcodebuild[14060:2105390]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/MAMIAN/Library/Developer/Xcode/DerivedData/WebDriverAgent-eeljxauaslzvcnapvmatskvoypfe/Logs/Test/C3C857A3-6248-405F-8D18-1FA984D29464/Session-WebDriverAgentRunner-2017-04-07_173700-o3rzhZ.log

>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:14054 2017-04-07 17:37:00.721 xcodebuild[14060:2105388] [MT] IDETestOperationsObserverDebug: (F01C30E1-CB9C-447F-86EA-369DC9134C01) Beginning test session WebDriverAgentRunner-F01C30E1-CB9C-447F-86EA-369DC9134C01 at 2017-04-07 17:37:00.720 with Xcode 8E162 on target <DVTiOSDevice: 0x7ffb097e7400> {
		deviceSerialNumber:         FK2QFSCDGRY9
		identifier:                 4fde6542011bd1a001a41edac73f0e492af603b4
		deviceClass:                iPhone
		deviceName:                 MAMIANiPhone6s
		deviceIdentifier:           4fde6542011bd1a001a41edac73f0e492af603b4
		productVersion:             10.3
		buildVersion:               14E277
		deviceSoftwareVersion:      10.3 (14E277)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        60338421760
		deviceAvailableCapacity:    25589170176
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7ffb094f5650 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3 (14E277))

>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:14054 writeDictToFile:1269 open failed for /var/folders/bp/n94rhkz94mg9x9zfvgdpm6r00000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/d223acf258b5afd25e3dde73bd1ab762/4fde6542011bd1a001a41edac73f0e492af603b4/ManifestCache.plist : No such file or directory

>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:14054 MDMCacheDirectoryManifest:1364 writeDictToFile failed to write to /var/folders/bp/n94rhkz94mg9x9zfvgdpm6r00000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/d223acf258b5afd25e3dde73bd1ab762/4fde6542011bd1a001a41edac73f0e492af603b4/ManifestCache.plist : No such file or directory

>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:14054 2017-04-07 17:37:02.212 xcodebuild[14060:2105388] Error Domain=com.apple.dtdevicekit Code=-402652994 "App installation failed" UserInfo={NSLocalizedFailureReason=This application's application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000011423a08d DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x000000011423a775 DTDK_AMDErrorToNSError + 789
	2   DTDeviceKitBase                     0x000000011427950d __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
	3   DVTFoundation                       0x0000000109feedcd DVTInvokeWithStrongOwnership + 75
	4   DTDeviceKitBase                     0x0000000114279248 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1133
	5   IDEiOSSupportCore                   0x000000011417c356 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.336 + 4154
	6   DVTFoundation                       0x000000010a118d56 __DVTDispatchAsync_block_invoke + 820
	7   libdispatch.dylib                   0x00007fffaa510524 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fffaa5078fc _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fffaa51d9a0 _dispatch_queue_serial_drain + 896
	10  libdispatch.dylib                   0x00007fffaa510306 _dispatch_queue_invoke + 1046
	11  libdispatch.dylib                   0x00007fffaa5096b5 _dispatch_root_queue_drain + 476
	12  libdispatch.dylib                   0x00007fffaa50948c _dispatch_worker_thread3 + 99
	13  libsystem_pthread.dylib             0x00007fffaa756616 _pthread_wqthread + 1299
	14  libsystem_pthread.dylib             0x00007fffaa7560f1 start_wqthread + 13
), NSLocalizedRecoverySuggestion=This application's application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed., NSLocalizedDescription=App installation failed}

>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:14054 2017-04-07 17:37:02.212 xcodebuild[14060:2105388] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:14054
Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **


>> xctest-client.js:176:14 [master] pid:14054 please check project: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:270:14 [master] pid:14054 killing deviceLogProc pid: 14057
>> xctest-client.js:275:14 [master] pid:14054 killing runnerProc pid: 14060
>> xctest-client.js:281:14 [master] pid:14054 killing iproxyProc pid: 14059
>> xctest-client.js:186:14 [master] pid:14054 xctest client exit with code: 65, signal: null
>> xctest-client.js:214:14 [master] pid:14054 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:150:16 [master] pid:14054 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:262:14 [master] pid:14054 Fail to start xctest: undefined
>> app-inspector:66:44 [master] pid:14054 undefined
(node:14054) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:14054 undefined
^C

```

我打开目标文件夹 `/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.1.6@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj` 可以正常运行

- app inspector version / 版本号: 1.2.23

- os version / 系统: 10.12.4

- device  information / 设备版本:

- terminal log / 终端输出信息:

**Comment by xudafeng** [comment]
update to latest version
