### ISSUE TITLE
安装失败，使用最新的Android SDK

### ISSUE THREAD

**Issue by LarkinZero** [macacajs/app-inspector#82]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:

- os version / 系统:OSX 10.12

- device  information / 设备版本:

- terminal log / 终端输出信息:

```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector
/usr/local/bin/app-inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector

> uiautomator-client@1.1.9 install /usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client
> node ./scripts/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "create uitest-project -n uiautomator-bootstrap -t android-24 -p ."

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
/usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:177
      throw e;
      ^

Error: setup failed
    at ChildProcess.createProcess.on.code (/usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:133:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib
└── app-inspector@1.2.23

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uiautomator-client@1.1.9 (node_modules/app-inspector/node_modules/uiautomator-client):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uiautomator-client@1.1.9 install: `node ./scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
@LarkinZero update to latest version
