### ISSUE TITLE
app inspector 连接android真机网页端显示Internal Server Error

### ISSUE THREAD

**Issue by Uglena** [macacajs/app-inspector#97]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:1.2.27 
-xcode: Version 8.3.2

- os version / 系统:10.12.4 (16E195)

- device  information / 设备版本: 小米5  android  6.0

- terminal log / 终端输出信息:

>> server.js:16:12 [master] pid:20876 server start with config:
 { port: 5678,
  verbose: true,
  udid: '90aef623',
  ip: '10.65.82.36',
  host: 'FIFINLI-MC1',
  loaded_time: '2017-05-16 15:20:30' }
>> app-inspector.js:43:12 [master] pid:20876 server start at: http://10.65.82.36:5678
>> UIAutomatorWD http server ready
>> Android device started: 90aef623
>> inspector start at: http://10.65.82.36:5678
  <-- GET /
>> proxy.js:56:14 [master] pid:20876 Proxy: /wd/hub/session/temp/source:GET to http://127.0.0.1:9001/wd/hub/session/temp/source:GET with body: null
>> proxy.js:84:20 [master] pid:20876 Got response with status 200: {"status":0,"value":"","sessionId":null}
>> Dump Android XML success, save to /usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/.temp/android.json

  TypeError: Cannot read property 'bounds' of undefined
      at adaptor (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/lib/android.js:27:13)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/lib/android.js:64:14)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  <-- GET /
>> proxy.js:56:14 [master] pid:20876 Proxy: /wd/hub/session/temp/source:GET to http://127.0.0.1:9001/wd/hub/session/temp/source:GET with body: null
>> proxy.js:84:20 [master] pid:20876 Got response with status 200: {"status":0,"value":"","sessionId":"temp"}
>> Dump Android XML success, save to /usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/.temp/android.json

  TypeError: Cannot read property 'bounds' of undefined
      at adaptor (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/lib/android.js:27:13)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/lib/android.js:64:14)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by Uglena** [comment]
@xudafeng

**Comment by mijiawei** [comment]
请问你是怎么解决的

**Comment by redpeer** [comment]
这个bug根本没有解决啊，为啥给关了
